### ISSUE TITLE
User-defined permissions are not yet supported with the built-in label button, right?

### ISSUE THREAD

**Issue by felinepc** [MicrosoftDocs/microsoft-365-docs#943] opened 2019-12-16 19:58 UTC
Labels with user-defined permissions (with the checkbox "In Word, Excel, PowerPoint and File Explorer prompt user for custom permissions" checked) are not showing under the Sensitivity button in Word/Excel/PowerPoint. I assume these are not yet supported and still require the AIP client?
Is there a plan to make these eventually available via the built-in labeling client?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0836a95-d3b7-3c43-d56b-5fb4ceeb4765
* Version Independent ID: 8a0d366b-5ff7-22de-7aba-6adbe0ea94ea
* Content: [Sensitivity labels in Office apps - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps#what-sensitivity-label-capabilities-are-supported-in-office-today)
* Content Source: [microsoft-365/compliance/sensitivity-labels-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-office-apps.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by VLG17** [comment] 2020-01-03 10:02
@felinepc At the moment there is no built-in option. You are correct, you require the client - AIP or the new Unified Labeling one.

**Comment by cabailey** [comment] 2020-01-03 21:04
@felinepc Correct, the label setting for user-defined permissions for Word, Excel, and PowerPoint for isn't currently supported for built-in labeling ("let users assign permissions" is "TBD" in the table) and you might find the following comparison table helpful if you haven't already seen it: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#compare-the-labeling-clients-for-windows-computers 

However, you say labels with this setting "are not showing under the Sensitivity button" for your ProPlus apps, and that's not my understanding.  The Azure Information Protection docs say the label is visible and can be applied, but without encryption: https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels#comparing-the-behavior-of-protection-settings-for-a-label   Can you confirm your experience?

**Comment by felinepc** [comment] 2020-01-04 00:25
>  The Azure Information Protection docs say the label is visible and can be applied, but without encryption: https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels#comparing-the-behavior-of-protection-settings-for-a-label Can you confirm your experience?

Yes I can confirm from my experience:
1. I create a custom label under "Confidential" and set it to let users assign permissions when applying. I checked both checkboxes related to Outlook and Word/Excel/PowerPoint (prompt user to assign permission).
 
2. This label does not show up under the Sensitivity button menu in Word/Excel/Powerpoint. Only the default labels show (All Employees etc). 

3. This label does show up in Outlook, and its behavior is as expected per the earlier checkbox (do-not-forward).

**Comment by cabailey** [comment] 2020-01-06 20:34
@felinepc  I think this is worth filing a support ticket for investigation.  I created a new label with this encryption setting "Let users assign permissions when they apply this label" and "In Word, PowerPoint, and Excel, prompt users to specify permissions" together with a footer to confirm when the label is applied.  And it behaved exactly as documented - the label was visible, I applied the label and no encryption was applied but the footer was.  

Then to more closely match your helpful repo steps, I created a new label but this time, as a sublabel of Confidential (and this time, selected both checkboxes to include "In Outlook, enforce restrictions equivalent to the Do Not Forward option".  And this time, the label isn't displayed.  It's less than 24 hours since I created and published this label, so it might be timing.  But in the meantime, I'm passing on my findings so you can try the same setting with a single label rather than a sublabel.

**Comment by cabailey** [comment] 2020-01-10 21:00
@felinepc  Did you open a support ticket for this?  Because I could repo this with my sublabel, it's now confirmed that there's a bug here and Support will be able to give you the latest information.  I think it's when both checkboxes are selected on the same label - for the label to display in Word, PowerPoint, and Excel, I had to remove the selection for Outlook.  Then the label displays in these apps (sublabel or main label).  But when both checkboxes are selected, the label doesn't display in these apps.

Because this is a confirmed issue (with a workaround) for the product, I'm closing this as a GitHub Issue.

**Closed by cabailey** 2020-01-10 21:00 UTC
Labels: compliance
