### ISSUE TITLE
How many users are protected?

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/microsoft-365-docs#10166] opened 2022-11-07 19:05 UTC
This page shows 301.  The Admin UI shows 350.  Can this discrepancy be cleared up?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2022-11-07 19:26
@chrislehr, you should open a support ticket about this. Right or wrong, the maximum value is currently 301 per [this other GitHub issue](https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10028).

Whether that's by design or a temporary problem is unknown at this point, which is why a support ticket is the best way forward. Plus, changing that 350 to 301 in the Microsoft 365 Defender portal is a code issue, which again, points to a support ticket.

Please report back here if you get any information that can help update the documentation.

**Comment by chrislehr** [comment] 2022-11-07 19:49
Is there a QA department that works somewhere between development and technical writing any more?  

![image](https://user-images.githubusercontent.com/10875667/200401038-8c14f04b-78d1-42c1-a236-b7fa989fe5e1.png)

My AntiPhishing policy holds 350 items before it errors in PowerShell.  It seems 350 (the setting in the UI) is what it is limited to and that the documentation might be incorrect.  

Please address the discrepancy in your documentation.

**Comment by chrislehr** [comment] 2022-11-07 19:50
![image](https://user-images.githubusercontent.com/10875667/200401413-1413edc7-0ed9-45c7-8a34-07ca206adfde.png)

**Comment by chrisda** [comment] 2022-11-07 21:10
I changed the number back to 350.

Thanks for the feedback.

Closing

**Closed by chrisda** 2022-11-07 21:10 UTC
Labels: Defender for Office 365
