### ISSUE TITLE
Incomplete information

### ISSUE THREAD

**Issue by NiteshSharma2K19** [MicrosoftDocs/microsoft-365-docs#2308] opened 2020-07-03 07:28 UTC
Hello Team,

The page is incomplete for the "Can I pilot Office 365 with just a few email ....". We're missing the steps to configure the connectors. Without connectors, the pilot will not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a11050-b442-7a48-0d37-9bce8908fc14
* Version Independent ID: 5456e564-2629-cfc2-dfc9-2b7934fcf43a
* Content: [Domains FAQ - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/domains-faq?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/domains-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/domains-faq.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by get-itips** [comment] 2020-07-22 11:47
Hello @NiteshSharma2K19 how are you?
Can you please expand your explanation of what you think needs to be improved in the article ?
Thanks

**Comment by NiteshSharma2K19** [comment] 2020-07-22 14:04
Hello @get-itips ,

I think someone removed the entire section from this page. There was a section, "Can I pilot Office 365 with just a few email ...." which is no longer available on this page. The information provided in that section was incomplete.

**Comment by get-itips** [comment] 2020-07-22 14:13
> Hello @get-itips ,
> 
> I think someone removed the entire section from this page. There was a section, "Can I pilot Office 365 with just a few email ...." which is no longer available on this page. The information provided in that section was incomplete.

Thanks for returning, yes you are right, reviewed the history of the document and that section was removed.

**Comment by get-itips** [comment] 2020-08-03 15:18
Hello, we will proceed closing this one as the information that lead to the creation of the issue is not present anymore in the article.

**Comment by yogkumgit** [comment] 2020-08-04 05:27
@get-itips  Thank you very much for the contribution and sharing this explanation. @NiteshSharma2K19 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-08-04 05:27 UTC
Labels: admin
