### ISSUE TITLE
SPO can NOT scan virus when upload by Microsoft Graph API

### ISSUE THREAD

**Issue by lethinh0510** [MicrosoftDocs/microsoft-365-docs#3396] opened 2020-11-10 02:58 UTC
Hi, 

I have a problem in SPO scan virus. 
When I upload virus file to SPO in browser. It scan OK.
But when I using Microsoft Graph API upload in FE. It didn't detected it virus. 

Thank you
![tempsnip](https://user-images.githubusercontent.com/10781387/98622084-3e49d200-233b-11eb-91b3-4903bdb5989b.png)

**Comment by msbemba** [comment] 2020-11-12 16:08
@lethinh0510 Thank you for your feedback. I was able to test and it worked both on the API and Browser. I would recommend you to contact the support team via the need help section on your Microsoft 365 Admin center. Also, In case if there are changes that can be made to the documents please do let us know.

@yogkumgit The feature is working correctly by design. However, We have requested the user to contact Support as this is a single-tenant or a file issue.

Thanks
Sri

**Comment by lethinh0510** [comment] 2020-11-13 03:32
> @lethinh0510 Thank you for your feedback. I was able to test and it worked both on the API and Browser. I would recommend you to contact the support team via the need help section on your Microsoft 365 Admin center. Also, In case if there are changes that can be made to the documents please do let us know.
> 
> @yogkumgit The feature is working correctly by design. However, We have requested the user to contact Support as this is a single-tenant or a file issue.
> 
> Thanks
> Sri

Thank you for your comment. 
First time I apply scan virus it working well, but since 1st November it NOT work. 
I upload same file.

**Comment by msbemba** [comment] 2020-11-13 05:59
@lethinh0510 That is interesting. I'd still recommend you to report the bug on the tenant to Microsoft support via Need help section. 

1)If this is a bug or a issue on your tenant - it will be fixed in the backend.
2)if this is a bug on M365, it can be routed to the correct team via support.

Thanks
Sri

**Comment by yogkumgit** [comment] 2020-11-13 08:12
@msbemba  Thank you very much for the contribution and sharing this explanation. @lethinh0510 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-11-13 08:12 UTC
Labels: admin
