### ISSUE TITLE
endpoint specifed as *.cloud.microsoft

### ISSUE THREAD

**Issue by gbordier** [MicrosoftDocs/microsoft-365-docs#10864] opened 2023-02-01 08:47 UTC
the microsoft Top Level Domain does not exist in public DNS, this this a Typo ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by jd1984** [comment] 2023-02-08 09:57
Hi @gbordier 

I suspect this may be due to "new IP Addresses and URLs published 30 days in advance of being active"

I just tried a nslookup for cloud.microsoft which returned

Non-authoritative answer:
Name:    cloud.microsoft
Addresses:  20.112.52.29
          20.53.203.50
          20.81.111.85
          20.84.181.62
          20.103.85.33

**Comment by yogkumgit** [comment] 2023-02-10 13:37
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment] 2023-02-14 19:28
@gbordier, thanks for reaching out. _*.cloud.microsoft_ is a valid domain that Microsoft 365 product scenarios will start using in the near future. Just like the rest of the published domains in the “Required” category, Microsoft asks customers to allow-list it in their network perimeters to avoid connectivity issues. -Kelley

**Closed by kelleyvice-msft** 2023-02-14 19:28 UTC
Labels: Enterprise, Microsoft submitter, writer-input-required

**Comment by gbordier** [comment] 2023-02-15 10:54
> 

Thanks for the tip, any way we can get a message created in Ofice 365 Message Center? nobody seems aware of this and a new top level domain may take some time beeing whitelisted in large customer organisations .

**Comment by jd1984** [comment] 2023-05-09 07:20
@gbordier this is now in Message Center as follows:

**cloud.microsoft domain for new Microsoft 365 apps**
MC550044 · Published 3 May 2023

Recently Microsoft provisioned the cloud.microsoft domain to provide a trusted, dedicated space to host our authenticated first-party SaaS experiences going forward. From May 2023 onward, all new Microsoft 365 first-party app experiences will launch on cloud.microsoft from the start. Existing Microsoft 365 workloads will also begin to transition to the new domain later this year. There will be further communications leading up to each workload transition.

**When this will happen:**

Customers will begin to see new apps using the cloud.microsoft domain in May 2023. Existing workloads will begin to transition no sooner than the second half of 2023.

**How this will affect your organization:**

No impacts to your organization’s existing Microsoft 365 experience are anticipated at this time: cloud.microsoft is currently being deployed only for new apps and services. Further communications will follow as existing workloads prepare to transition to the new domain.
Users may be wondering about how the domain looks, due to the absence of a “.com” or other familiar TLD. This is by design, as this top-level domain is Microsoft’s own TLD, which allows for additional security and protection against spoofing.

**What you need to do to prepare:**

Educate users to recognize and expect cloud.microsoft as a key domain for Microsoft cloud experiences
Admins should ensure that *cloud.microsoft is included on network allow lists. This should require no action if standard[ Microsoft network guidance on domains and service endpoints](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges) is being followed.


[Additional information](https://aka.ms/o365ips)
[Blog](https://aka.ms/domainunification)
