### ISSUE TITLE
Add information for GoBD in Germany

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#3137] opened 2020-10-13 21:31 UTC
Hello,

it would be great if Microsoft provides information like an overview or instructions to work on to become compliant with German gov guidance 'Grund­sät­ze zur ord­nungs­mä­ßi­gen Füh­rung und Auf­be­wah­rung von Bü­chern, Auf­zeich­nun­gen und Un­ter­la­gen in elek­tro­ni­scher Form so­wie zum Da­ten­zu­griff (GoBD)' as like as it does for other compliance or certification topics. For details see this document: https://www.bundesfinanzministerium.de/Content/DE/Downloads/BMF_Schreiben/Weitere_Steuerthemen/Abgabenordnung/2019-11-28-GoBD.html.

This is a very important set of guidances expected to be fulfilled by modern businesses in Germany and published by the German government.

I'm aware it can't be covered fully in detail but at least some basics or references to relevant documentation would be great.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 556e9d3f-080a-d2e0-0c23-e35e548efccd
* Version Independent ID: 30fbaca4-b260-1dd4-8d54-97c84a247000
* Content: [Microsoft 365 solution catalog - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/microsoft-365-solution-catalog?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/microsoft-365-solution-catalog.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/microsoft-365-solution-catalog.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment] 2020-10-15 20:06
@robmazz I have checked and found that the references are legit. However, I feel these need to be added/referenced only on the german version of the document(if there is one) and not required for the global audience. I would like to know your feedback before I make any changes to it.

Thanks
Sri

**Comment by GiantCrocodile** [comment] 2020-10-15 20:16
@msbemba I just opened this issue for this article as it was the most fitting article I could open an issue for. I'm aware that this shouldn't be in the global audience article. I think an article dedicated to German businesses would be great as we have other articles about national regulations/laws/standards too. That would fit there.

**Comment by robmazz** [comment] 2020-10-15 20:40
@msbemba - very unlikely that references can be added to the topic and only displayed in the de-de instance, but I'll double-check with the localization team to confirm.

**Comment by yogkumgit** [comment] 2020-11-16 08:08
@robmazz Any reply from localization team. Please update. Thanks

**Comment by robmazz** [comment] 2020-11-18 20:27
@msbemba - localization team does not support one-off publishing. Even if the German version was customized, it would be overwritten by any other merged changed to the topic. Closing as by design.

**Closed by robmazz** 2020-11-18 20:27 UTC
Labels: compliance
