### ISSUE TITLE
Preferred contact method Email is missing

### ISSUE THREAD

**Issue by TobiasAT** [MicrosoftDocs/microsoft-365-docs#5568] opened 2021-07-07 13:48 UTC
I recently saw for a new support request the preferred contact method Email is missing for a specific account. The account can just select phone. The account is Global Admin. Other accounts see both options. I have no clue why Email is missing just for one account. Any ideas?

Regards
Tobias

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9fe16db-f502-6d93-8e0a-d4b892064416
* Version Independent ID: 1ecf27fd-ed6c-f387-b56a-80673117e480
* Content: [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide)
* Content Source: [microsoft-365/business-video/get-help-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/get-help-support.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment] 2021-07-12 15:41
@TobiasAT Thank you for your feedback. I was able to test it with/without a license assigned to a Global and could not replicate the issue. DId you get a chance to test it via another browser or maybe in-private mode?

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment] 2021-07-14 07:07
@msbemba Thank you very much for the contribution and sharing this explanation. @TobiasAT Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2021-07-14 07:08 UTC
Labels: business, doc-enhancement

**Comment by TobiasAT** [comment] 2021-07-14 07:23
I still have the issue (was busy for the last days). Private mode does not help. It's also just in one tenant.

![image](https://user-images.githubusercontent.com/7470044/125580470-0e36e921-e92b-406d-8ca4-83d5ac8cb493.png)

**Comment by msbemba** [comment] 2021-07-14 09:37
@TobiasAT Thank you for the response. I'd recommend you contact Microsoft support and have them check in the backend. I have tested multiple tenants and could not reproduce the issue, so this could be an issue related to the account/tenant.

If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide).

Hope this helps!

Thanks
Sri
