### ISSUE TITLE
Microsoft test answer not in alignment with given page

### ISSUE THREAD

**Issue by drewjames1234** [MicrosoftDocs/microsoft-365-docs#4307] opened 2021-03-02 21:27 UTC
Please see question below (on administrator past exam).  The suggested correct answer is D.  I can't find any indication of the phrase Network Monitor.  This page is supposed to be the closest relevant document.

Could Microsoft synchronise information with what people are likely to be tested on?

Your company has a Microsoft 365 subscription.
When making voice calls from Microsoft Teams, users report poor call quality at specific times of the
day.
You need to verify whether Quality of Service (QoS) is being applied to the calls.
What should you use?
A. the Microsoft Teams client
B. Microsoft Call Quality Dashboard
C. Network Testing Companion
**D. Network Monitor**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147fb47a-99b2-f8ef-9ca6-35696d49c3fb
* Version Independent ID: b2f1b521-f231-48c2-b61f-f71bf9248d1c
* Content: [Collaborate with guests in a team](https://docs.microsoft.com/en-US/microsoft-365/solutions/collaborate-as-team?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-as-team.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-as-team.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment] 2021-03-05 13:42
@MikePlumleyMSFT  Please add your comment and help us in resolving this issue. Thanks.

**Comment by MikePlumleyMSFT** [comment] 2021-03-05 13:44
@yogkumgit the issue does not appear to be related to this article.

**Comment by yogkumgit** [comment] 2021-04-09 16:11
@drewjames1234  as the issue is not related with this article, We proceed here to close it.  If you see a documentation update is required, please feel free to open an issue for the same.  Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2021-04-09 16:12 UTC
Labels: solutions
