### ISSUE TITLE
Please add below note/Pointers in the Technet with the redirection link attached 

### ISSUE THREAD

**Issue by MithunRathinam** [MicrosoftDocs/microsoft-365-docs#8964] opened 2022-06-20 20:15 UTC
1) Under the section "Configure the "Block the following URLs" list in the Microsoft 365 Defender portal"

"You can now manage block entries in the Tenant Allow/Block List. (https://docs.microsoft.com/microsoft-365/security/office-365-security/tenant-allow-block-list)
The Global Settings Block List will be turned off in the coming months".

Note: Organizations will no longer have the ability to add to the URL/Domain entries to the Safe Links Block List in the Global Settings flyout and we will attempt to migrate all the entries in an organization's Safe Links Block List to TABL on their behalf. Any entry migrated from the Safe Links Block List to the Tenant Allow/Block List will adopt the behavior of TABL. This means that any message with the URL present will be moved to Quarantine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f078ade-1f5b-ca3f-190a-8182a4f3d155
* Version Independent ID: 2556b079-c975-79f7-bad0-44ba3fc18ed5
* Content: [Configure global settings for Safe Links settings in Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-global-settings-for-safe-links?view=o365-worldwide#configure-the-block-the-following-urls-list-in-the-microsoft-365-defender-portal)
* Content Source: [microsoft-365/security/office-365-security/configure-global-settings-for-safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-global-settings-for-safe-links.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2022-06-21 17:01
Closing as duplicate of #8963

**Closed by chrisda** 2022-06-21 17:01 UTC
Labels: duplicate, Defender for Office 365
