### ISSUE TITLE
Auto-apply feature works with E3 license too

### ISSUE THREAD

**Issue by DeepRaj98** [MicrosoftDocs/microsoft-365-docs#937] opened 2019-12-16 07:23 UTC
Hi Team, 
The documentation says that the auto-apply labels capability needs to have E5 license, but in my testing, it works with E3 license too. Also, as per discussion on the MS case- 17831188, we found that once this capability is out of preview, it will be limited based on E5 license. Could you confirm if auto-apply labels feature for Emails is still in preview? or if it is already out of preview, will it work completely fine with E3 license?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ad620-438b-dae8-26df-258406e97152
* Version Independent ID: 6850f86a-00b4-cc5d-b1eb-ae48d5f7025a
* Content: [Overview of retention labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/labels#feedback)
* Content Source: [microsoft-365/compliance/labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by GiantCrocodile** [comment] 2019-12-26 01:15
I think your answer is related to #864 and thus it is E5 feature only and doesn't works properly without a license (at least in my case for Exchange Online and SharePoint Online). Why do you think it does work with E3? What did you test?

**Comment by DeepRaj98** [comment] 2019-12-26 08:51
My query is more for Exchange location (#864 is for Sharepoint). I have a test user who has E3 license and the admin also has same license. I have a retention label created. And it was automatically applied to the content in user mailbox. So, in my testing,it works with E3 license.

**Comment by GiantCrocodile** [comment] 2019-12-26 10:43
Ok, I understand the difference and what you did. This is interesting for me because I did try Exchange Online and auto-labeling too and it didn't work for me back then. I'm curious for a reply from Microsoft. Thanks for bringing this up @DeepRaj98!

**Comment by cabailey** [comment] 2020-01-06 20:17
@GiantCrocodile and @DeepRaj98  I investigated this and it was confirmed from the PM that auto-labeling is GA (only trainable classifiers are in preview) and requires an E5 license, although not enforced at this time. So if you have a mix of E3 and E5 licenses for your users, when you're configuring your auto-labeling policy, you must select the "Choose recipients" or "Exclude recipients" on the "Choose locations" page in the wizard to make sure auto-labeling applies only to users with the required license.  The engineering team is investing reporting to help with accidental misconfiguration for users who have this policy assigned without the required license.

**Comment by DeepRaj98** [comment] 2020-01-08 14:11
Thanks @Cabailey for confirming.

**Comment by mypil** [comment] 2020-01-08 16:51
@DeepRaj98 @GiantCrocodile - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by cabailey so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Closed by mypil** 2020-01-08 16:51 UTC
Labels: compliance

**Comment by DeepRaj98** [comment] 2020-01-10 18:28
@cabailey could you help me with one more detail; a note in the document states below- “ The capability to apply labels automatically requires an Office 365 Enterprise E5 license for each user who has permissions to edit content that's been automatically labeled in a site or mailbox. Users who simply have read-only access do not require a license.”
So, if we deploy auto-apply label to some mails of users as per the query based condition and if these users don’t need to edit those mails; we don’t need E5 licenses to be assigned to them?
We were told that all users who get auto-applied label need to have E5 licenses.

**Comment by cabailey** [comment] 2020-01-10 20:50
@DeepRaj98  Checking … but my understanding is every user whose mailbox is selected for auto-labeling needs an E5 license.  I think the licensing statement needs finessing for email & checking up on this before updating in the doc.

**Comment by DeepRaj98** [comment] 2020-01-13 10:46
Thanks @cabailey for getting this verified. The confirmation will help as we are looking for some solution and this feature looks best match but the E5 licensing is not yet an offered license for all users. This will help in modifying the note too if all users need E5 for using this feature (even if they don't need to modify any content in email).

**Comment by DeepRaj98** [comment] 2020-06-25 14:00
Hello Team,

Wanted to follow up on this. :)

DeepRaj

**Comment by cabailey** [comment] 2020-06-25 14:21
@DeepRaj98  On request from the team who manages licensing, we have removed all ad-hoc licensing statements from this page (and others for retention) and replaced them with a link at the top of the pages to a single, authoritative source. From that page, you'll find links to a supplemental spreadsheet to download (PDF or Excel) with individual statements per feature.  If you have feedback about the licensing statements, you can post them on that page for the licensing team to review.
