### ISSUE TITLE
Invalid FROM address

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/microsoft-365-docs#10136] opened 2022-11-03 09:33 UTC
Invalid from Address should include email addresses containing a space like <firstname secondname@contoso.com>

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd8eda3-422f-0ca5-328c-cf049daf296e
* Version Independent ID: 24a28789-1473-dc1f-aa94-67015c1ff12d
* Content: [How EOP validates the From address to prevent phishing - Office 365](https://learn.microsoft.com/en-gb/microsoft-365/security/office-365-security/how-office-365-validates-the-from-address?redirectSourcePath=%252fen-us%252farticle%252fHow-Office-365-validates-the-From-address-to-prevent-phishing-eef8408b-54d3-4d7d-9cf7-ad2af10b2e0e&view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/how-office-365-validates-the-from-address.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/how-office-365-validates-the-from-address.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2022-11-03 16:24
I'm closing this as a duplicate of #10135

**Closed by chrisda** 2022-11-03 16:24 UTC
Labels: duplicate, Defender for Office 365

**Comment by JeroenDronkers** [comment] 2022-11-03 16:30
Hello Chris,

Yes I had to create another one because the first one seemed to have failed.

The issue is that we don’t support Email addresses with spaces like <email ***@***.******@***.***>>

It would be nice to have this added to the article so that we can refer customer to it.


Many thanks!


Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
***@***.******@***.***>

[abc]
﻿
Team Manager | Frances Early ***@***.******@***.***>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center
