### ISSUE TITLE
Change of Organization Name

### ISSUE THREAD

**Issue by paulaustin-automutatio** [MicrosoftDocs/microsoft-365-docs#5244] opened 2021-06-07 20:29 UTC
[Enter feedback here]

Somehow are organization name got changed we don't know how. It ended up being the name of the user rather than the company name.

Contrary to the following.

`Currently, updating the organization name does not update it for configured clients.`

I ended up with older directories synced using the old name, new synced directories with the new name.

Changing it back didn't revert to the correct name when I disconnected, uninstalled one drive and tried again. Including deleting the identity in the registry for OneDrive. It still shows the incorrect org name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecea09f5-957a-4674-0449-def4a1de21a4
* Version Independent ID: 53c2bbeb-daf8-56cd-f821-aa6e7e2fee92
* Content: [Change your organization's address, technical contact, and more - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/change-address-contact-and-more?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/change-address-contact-and-more.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/change-address-contact-and-more.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment] 2021-06-10 18:38
@paulaustin-automutatio Thank you for your feedback. Ideally, when you sign out and sign back into one drive it should sync with the new organization name. This sounds more like a cached setting that gets fixed after 24-48 hours. Do you still see the old organization name in file explorer ?

Thanks
Sri

**Comment by paulaustin-automutatio** [comment] 2021-06-10 18:58
@msbemba I have tried disconnecting the accounts, uninstalling and then installing OneDrive, deleting registry entries and on a different machine that wasn't currently syncing.

Plus on a number of web apps (e.g. Bing company home) it sometimes showed up the wrong organization name.

So it looks like services at MS are caching the organization name and not propagating the change quickly enough or not accepting the change.

**Comment by msbemba** [comment] 2021-06-14 14:11
@paulaustin-automutatio Thank you for your feedback. I could not reproduce this issue, This could be an issue with your tenant. The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 

Thanks
Sri

**Comment by paulaustin-automutatio** [comment] 2021-06-14 16:46
I’ve been trying it through Microsoft Support but haven’t found anyone who can actually look at the problem.

**Comment by yogkumgit** [comment] 2021-06-15 10:44
@msbemba  Thank you very much for the contribution and sharing this explanation. @paulaustin-automutatio Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it as here, we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2021-06-15 10:45 UTC
Labels: admin, support-request
