### ISSUE TITLE
Purge or Delete

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/microsoft-365-docs#7545] opened 2022-01-28 21:15 UTC
So you've done the eDiscovery search, found the message you want, how do you then Purge or Delete the message?  (Your boss has asked you to remove a rant from a disgruntled employee in a teams meeting channel yet even the Organizer of that meeting has no delete ability etc...?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb41d287-f954-dc84-782c-de8fa3c1ea0d
* Version Independent ID: 0081aa8b-87dd-aef2-aaeb-61caa8f20351
* Content: [Teams workflow in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/teams-workflow-in-advanced-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/teams-workflow-in-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/teams-workflow-in-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment] 2022-02-01 17:02
@mattsmacblog Closing as a duplicate of the other github issue opened about the same issue. As per the search and purge article you cited, you can't use eDiscovery tools to delete Teams content. I would suggest you contact Microsoft Support concerning this issue.

**Closed by markjjo** 2022-02-01 17:02 UTC
Labels: compliance
