### ISSUE TITLE
Out of date screenshots

### ISSUE THREAD

**Issue by Datatech-AK** [MicrosoftDocs/microsoft-365-docs#13242] opened 2023-11-29 23:17 UTC
The process for using mail headers to bypass the focused inbox includes screenshots that no longer match the current Exchange Online interface; these should be updated to address the current UI.  Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88a29483-a070-ccc1-b064-176dfa49d5e9
* Version Independent ID: bad082c0-9ca2-0ade-6b1f-0ba5ac26017b
* Content: [Configure Focused Inbox for everyone in your organization - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/setup/configure-focused-inbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/configure-focused-inbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/configure-focused-inbox.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment] 2023-12-05 14:08
@Datatech-AK Thank you for you feedback. We will update the Screenshots on the document  shortly. 

Thanks
Sri

**Comment by Datatech-AK** [comment] 2023-12-05 16:57
Thank you very much, I greatly appreciate it!

[Logo]<https://www.bbna.com/>
Kyle Hardin
Network Administrator | BBNA
p: (907) 842-6203
e: ***@***.***
www.bbna.com<http://www.bbna.com/>

***@***.***?anonymous&ep=bwmEmailSignature>         Book time to meet with ***@***.***?anonymous&ep=bwmEmailSignature>
________________________________

**Comment by yogkumgit** [comment] 2023-12-06 12:14
@msbemba

**Comment by officedocspr5** [comment] 2023-12-08 00:59
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by yogkumgit** [comment] 2023-12-12 05:24
@kwekuako Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment] 2023-12-15 04:59
@Datatech-AK author confirmed that article is updated. Closing. Thanks

**Closed by yogkumgit** 2023-12-15 04:59 UTC
Labels: admin, writer-input-required
