### ISSUE TITLE
Bookings is stuck on a deleted booking calendar

### ISSUE THREAD

**Issue by ahmetarslan2020** [MicrosoftDocs/microsoft-365-docs#5490] opened 2021-06-29 15:16 UTC
[Enter feedback here]

We deleted the bookings calendar but user still sees it when logins into the bookings web app. Also, the User cannot add a new bookings calendar. Notting comes out from the search when trying to open a new calendar.  It looks like is stuck on a deleted booking calendar. Tried with a private/incognito browser nothing comes out from the search.

Please advice.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa612c0e-c089-8b3e-8e2e-dd12b6fc382c
* Version Independent ID: fa014ea6-7aa2-b2bd-d913-165c3241675f
* Content: [Delete a booking calendar](https://docs.microsoft.com/en-us/microsoft-365/bookings/delete-calendar?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/delete-calendar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/delete-calendar.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by nalhemyariirexorg** [comment] 2021-06-29 18:32
I would love to hear the resolution, we're facing the same issue in my tenant?

**Comment by nalhemyariirexorg** [comment] 2021-06-29 18:33
Also I hope the answer won't be create a new booking to get out of the stuck deleted one!

**Comment by msbemba** [comment] 2021-07-05 08:08
@ahmetarslan2020 Thank you for your feedback. I was not able to reproduce the problem and this seems like a bug in the tenant. The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 

Thanks
Sri

**Comment by ahmetarslan2020** [comment] 2021-07-05 14:23
Hello Sri,

Thanks for checking that!. I have submitted a service ticket to Microsoft Office 365 Team.

Ahmet Arslan

**Comment by yogkumgit** [comment] 2021-07-06 09:12
@msbemba  Thank you very much for the contribution and sharing this explanation. @ahmetarslan2020 thanks for opening a service ticket in please follow with them for the resolution. We proceed here to close it as here, we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2021-07-06 09:13 UTC
Labels: Bookings, support-request
