### ISSUE TITLE
New Case action - Manage pseudonymize

### ISSUE THREAD

**Issue by ItaloDuarte** [MicrosoftDocs/microsoft-365-docs#8306] opened 2022-04-13 14:44 UTC
There is a new case action called Manage pseudonymize and there is no information about this action.
we would like to have information about it on this page, because it is already explaining all actions here.
Thank you

**Comment by denisebmsft** [comment] 2022-04-13 19:11
Hello @ItaloDuarte. Can you please tell us to which article your feedback applies? This information will help us route the issue to the correct writer. Thanks!

**Comment by denisebmsft** [comment] 2022-04-13 19:12
Duplicate of https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8307

**Closed by denisebmsft** 2022-04-13 19:12 UTC
Labels: compliance
