### ISSUE TITLE
Microsoft Defender Linux, nfs scanning/real-time protection

### ISSUE THREAD

**Issue by birdmn** [MicrosoftDocs/microsoft-365-docs#8540] opened 2022-05-10 10:43 UTC
Hello,
we're running Microsoft Defender on Ubuntu 20.04 computers (version 101.65.77) and experiencing strange behavior with NFSv3 and NFSv4 mounts. Mounts are done with sec=krb5p or krb5i.

NFSv4 with krb5p or krb5i: mdatp is not able to do real-time scans while reading or executing known malicious files (e.g. eicar testfile).

NFSv3 with krb5p or krb5i: on some computers mdatp is able to detect malicious files while interacting with them ("cat eicar.txt" gives "cat: eicar.txt: Operation not permitted" and alarm is displayed in Defender Portal) but e.g. "tail eicar.txt" runs ok with no alarms. On some computers mdatp does not detect malicious files while interacting.

All the computers used for testing are running the same mdatp configurations, all are onboarded and no health issues are shown with command "mdatp health".

What does it mean that nfs is supported filesystem with mdatp? To me it seems that mdatp + nfs is not working reliably (as AV should).

**Comment by birdmn** [comment] 2022-05-12 06:35
As an addition: Defender does not react to malicious files even with sec=sys using NFSv4.

**Comment by msbemba** [comment] 2022-05-16 07:06
@birdmn Thank you for your feedback. By design, NFS is a supported files system. This looks like a bug and can be reported directly to our support team via the need help option in the admin center.

We handle only document changes, hence the support team will be able to fix it, if it is found as a bug it will be escalated internally to the product group.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment] 2022-05-17 02:57
@msbemba Thank you very much for the contribution and sharing this explanation. @birdmn Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2022-05-17 02:57 UTC
Labels: Defender for Endpoint, support-request
