### ISSUE TITLE
Downloaded PDF incomplete

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/microsoft-365-docs#7755] opened 2022-02-18 20:33 UTC
The downloadable PDF is incomplete.  It generates a 506 page document but pages after 224 are all blank.
This is in the midst of the Workload solutions and scenarios -> Administration and migration -> Tenant management -> Step 2. Optimal Networking   section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5603021e-457e-dfca-5f5c-6ab09be9c9b0
* Version Independent ID: 0f06f7a0-89a4-297a-cfe0-2548f95dbcd9
* Content: [Microsoft 365 Enterprise architecture design principles](https://docs.microsoft.com/en-us/microsoft-365/solutions/design-principles?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/design-principles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/design-principles.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @samanro
* Microsoft Alias: **samanro**

**Comment by yogkumgit** [comment] 2022-02-22 09:56
@samanro Please help us in resolving this issue. Thanks

**Comment by samanro** [comment] 2022-02-22 16:00
@dstrome , do you know if this issue would be with the platform? How do we troubleshoot PDF downloads from the library?

**Comment by dstrome** [comment] 2022-02-22 19:57
@traya1 - please take a look at what's going on with the PDF generation for this docset.

**Comment by traya1** [comment] 2022-02-22 19:59
Can do

**Comment by traya1** [comment] 2022-02-23 18:17
Hi @[bholzmmc](https://github.com/bholzmmc),

Can you try accessing the downloadable PDF on your end again? I ran a manual PDF generation and I now see no issues with the PDF, on my end, but what to confirm if the issue is resolved on your end.

I'm still looking into what may have caused the issue in the first place.

Thanks!

**Comment by bholzmmc** [comment] 2022-02-23 20:22
Looks fine now.

You can close the Issue.

Brian

**Closed** 2022-02-24 11:22 UTC
Labels: solutions, doc-enhancement, writer-input-required
