### ISSUE TITLE
The sample in the section "Prepare for the new Exchange Online certificate" is not longer valid.

### ISSUE THREAD

**Issue by dfife** [MicrosoftDocs/microsoft-365-docs#3342] opened 2020-11-03 10:36 UTC
[Enter feedback here]

The sample in the section "Prepare for the new Exchange Online certificate" is not longer valid. Please update the command and needed certificate list to point to valid URLs. The listed command:

certutil -URL https://crl.globalsign.com/gsorganizationvalsha2g3.crl

 is no longer valid and fails 100% of the time.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f032f4f-c4b0-9133-aaab-a44f28910472
* Version Independent ID: ffc3850e-1378-850b-5cd6-bde82db00f25
* Content: [How Exchange Online uses TLS to secure email connections - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/exchange-online-uses-tls-to-secure-email-connections?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/exchange-online-uses-tls-to-secure-email-connections.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/exchange-online-uses-tls-to-secure-email-connections.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment] 2020-11-16 17:24
@dfife Thank you for your feedback. I was able to test this in two instances and it works without any issues. What is the error message that you receive? Depending on the error you may have to contact the support team to identify the root cause and fix the issue.

Thanks
Sri

**Comment by yogkumgit** [comment] 2020-11-18 09:38
@msbemba Thank you very much for the contribution and sharing this explanation. @dfife Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-11-18 09:38 UTC
Labels: compliance
