### ISSUE TITLE
Columns added to wrong Content Type

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/microsoft-365-docs#5771] opened 2021-07-29 14:21 UTC
I created a Model for an _existing_ "Scope of Work" content type and applied it to a library. The columns that were included in the "Scope of Work" content type were added correctly (highlighted green), but the Syntex-specific columns (yellow highlight) are added to the **default content type** in the library, "Project Document", rather than the actual content type.

![image](https://user-images.githubusercontent.com/9206808/127508265-f6b6b8f0-8291-4239-9249-dd15cb36c132.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3000f1d8-7c81-d9c2-adfc-fa5f76612d73
* Version Independent ID: 9fbcb2c9-69d3-c825-73bb-1547158ee051
* Content: [Apply a document understanding model to a document library](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/apply-a-model)
* Content Source: [microsoft-365/contentunderstanding/apply-a-model.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/apply-a-model.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by yogkumgit** [comment] 2021-08-04 12:38
@chuckedmonson Please help us in resolving this issue. Thanks

**Comment by chuckedmonson** [comment] 2021-08-04 19:52
@seansquires -- Can you please advise sparkitect about the inquiry above? Thank you.

**Comment by chuckedmonson** [comment] 2021-08-06 15:45
@sparkitect -- Can you please provide more details, such as the URL you were trying to apply the model to? Thank you.

**Comment by sparkitect** [comment] 2021-08-06 17:43
> @sparkitect -- Can you please provide more details, such as the URL you were trying to apply the model to? Thank you.

I fail to see how the URL of the library is relevant, as you wouldn't have access to it.

I applied the model to a Document Library that already had other Content Types allowed - you should be able to reproduce this with _any_ library.

Expected behavior: Columns which are added to the library, by way of publishing a Document Understanding model to the library, should **only** be added to the Content Type that the model is associated with. Any other Content Types already in the library should be left alone.

Actual behavior: Model-specific columns are added to the _default_ Content Type in the target library, even if that isn't the Content Type associated w/ the model.

**Comment by chuckedmonson** [comment] 2021-08-06 22:18
Hi, @sparkitect -- Thank you for the reply. Because the actual behavior is different than expected, we would like to analyze the probable cause. It could be that the taxonomy field in the content center is corrupted. Can you tell me whether this is the source URL: "lacombecounty.sharepoint.com"? Thank you.

**Comment by sparkitect** [comment] 2021-08-06 22:41
Though I am working with a customer in that tenant, we haven't yet made it to this step over there.

I found this in our own tenant "sharesquared.sharepoint.com"

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sparkitect** [comment] 2021-08-12 00:42
I can’t remember when it happened, so I’ve just reproduced it (8/11/2021 ~5:35pm Pacific).

Before:
***@***.***

After:
***@***.***
(green is expected, red is not and should be “Used In” Scope of Work)

Also, the first TWO times I clicked the Add button, I got this error message:
***@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by sparkitect** [comment] 2021-08-12 00:46
I can’t remember when it happened, so I’ve just reproduced it (8/11/2021 ~5:35pm Pacific).

Before:
![image](https://user-images.githubusercontent.com/9206808/129121327-ce5c2390-7076-4b79-a584-e8237c502928.png)

After:
![image](https://user-images.githubusercontent.com/9206808/129121342-69539348-b656-4646-b2ba-4538c87e1e6b.png)
(green is expected, red is not and should be “Used In” Scope of Work)

Also, the first TWO times I clicked the Add button, I got this error message:
![image](https://user-images.githubusercontent.com/9206808/129121365-7eb01b71-01b6-4555-b691-eba59e1dbe08.png)

**Comment by chuckedmonson** [comment] 2021-08-16 17:17
@sparkitect -- We looked into this, here’s what we see:
In terms of the fields, each of these are required by all models, and is added to the library instead of a specific content type: _ModelId , Classification Date, confident score, Corrected, ModelUrl, ModelVersion.
Columns that are specific to an individual model are added to the specific content type, like “Business Unit, Document Owner, Document Type”.
This was by design to ensure all the content types that come with models share the same common fields. If this is unfavorable for your scenario, we’d love to know more so we can consider changes in the future.
Finally, the reason you see an error is you have a managed metadata field “Document Type” whose term set can’t be found, you’ll want to look into this (perhaps it has been deleted). We absolutely acknowledge that the error message isn’t helpful, we will change that to be more explicit about not being able to find the term set, we’ll get that updated. Thank you for your feedback!

**Comment by sparkitect** [comment] 2021-08-16 18:09
Ok, I understand now.
As long as the non-extractor columns are hidden from the forms it should be fine.

**Closed** 2021-08-16 18:09 UTC
Labels: enterprise, writer-input-required
