### ISSUE TITLE
Audit Delegate Send is not supported in EXO. 

### ISSUE THREAD

**Issue by dougsbaker** [MicrosoftDocs/microsoft-365-docs#5241] opened 2021-06-07 15:37 UTC
If you try to run the update command it errors with this code. 
Invalid audit operation specified. Supported audit operations for Delegate are None, Create, FolderBind, SendAs, SendOnBehalf, SoftDelete, HardDelete, Update, Move, MoveToDeletedItems and UpdateFolderPermissions.
    + CategoryInfo          : NotSpecified: (Microsoft.Excha...asks.SetMailbox:SetMailbox) [], RecipientTaskException
    + FullyQualifiedErrorId : [Server=MWHPR08MB3373,RequestId=b05dd17f-8280-4193-890a-9d3b251db699,TimeStamp=6/7/2021 3:35:19 PM] [FailureCategory=Cmdlet-RecipientTaskException] 5755929A
    + PSComputerName        : outlook.office365.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aac99b-5c65-74d3-7610-b7ba4fcac493
* Version Independent ID: a0b2ab87-7d52-3429-630e-6b7a316b5f23
* Content: [Manage mailbox auditing - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-mailbox-auditing?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-mailbox-auditing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-mailbox-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2021-06-07 16:20
@dougsbaker, which command are we talking about?

**Comment by dougsbaker** [comment] 2021-06-07 19:28
Sorry about that, I think this is just my lack of understanding on how the commands to set are supposed to work. 

Set-Mailbox doug@dougsbaker.com -AuditDelegate @{add="Send"}

Invalid audit operation specified. Supported audit operations for Delegate are None, Create, FolderBind, SendAs, SendOnBehalf, SoftDelete, HardDelete, Update, Move, MoveToDeletedItems and UpdateFolderPermissions.

**Comment by chrisda** [comment] 2021-06-08 22:46
@dougsbaker, check out the description in the table for the Send value:

> This value is only available for E5 or E5 Compliance add-on subscription users. For more information, see [Set up Advanced Audit for users](https://docs.microsoft.com/microsoft-365/compliance/set-up-advanced-audit).

So could we be dealing with a licensing issue here?

**Comment by chrisda** [comment] 2021-06-09 20:36
@dougsbaker, I confirmed that Send is not available for AuditDelegate even in an E5 organization with the correct licenses. I updated the topic accordingly.

What I don't know is whether this is by design or just some unintentional problem. I'm seeking guidance from experts.

**Comment by dougsbaker** [comment] 2021-06-10 01:26
Sorry, yes this was for an E5 subscription I was testing.

**Comment by yogkumgit** [comment] 2021-06-14 12:39
@dougsbaker Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2021-06-14 12:40 UTC
Labels: Defender for Office 365, doc-enhancement
