### ISSUE TITLE
Bug with selecting the domain to which a policy applies

### ISSUE THREAD

**Issue by badsector-82** [MicrosoftDocs/microsoft-365-docs#6401] opened 2021-09-22 15:53 UTC
I have a tenant with several domains. Their names are like this - domain.com, another.domain.com, yetanother.domain.com, etc. If in the policy I put "domain.com" it applies to all other domains in the tenant as well. As if the filter is "recipientAddress -like '*domain.com'" instead of "recipientAddress -like '*@domain.com'".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed2861d-860e-5d27-9259-fb9db2187f4b
* Version Independent ID: 09ef5622-3a7e-30f9-00f9-4c5578f8e1ca
* Content: [Configure spam filter policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-your-spam-filter-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2021-09-22 21:54
@badsector-82, I presume your talking about the Allowed Domains list or the Blocked Domains list? That behavior could be by design. Your best bet is to open a support case to see what they say.

**Comment by badsector-82** [comment] 2021-09-23 18:00
> 
> 
> @badsector-82, I presume your talking about the Allowed Domains list or the Blocked Domains list? That behavior could be by design. Your best bet is to open a support case to see what they say.

No, I'm not talking about Allowed Domains list, or the Blocked Domains list. I'm talking about the list of domains, that the policy should be applied to. That's the first thing after the name, you have to choose when creating a new policy. Here's a screenshot to be more clear - https://i.imgur.com/vV4DdWB.png

**Comment by chrisda** [comment] 2021-09-23 21:19
@badsector-82, OK. That "Applies to" logic for domains should be the same for any/all types of policies.

If it's only working the way you describe for anti-spam policies, or it works the same for all types of policies, but you don't think it should work that way, then your best course of action is to open a support case.

**Comment by yogkumgit** [comment] 2021-09-24 11:32
@badsector-82 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2021-09-24 11:33 UTC
Labels: Defender for Office 365, doc-enhancement
