### ISSUE TITLE
The documentation mentions a feature that is not working

### ISSUE THREAD

**Issue by QuintenPXS** [MicrosoftDocs/microsoft-365-docs#8030] opened 2022-03-16 10:24 UTC
Dears,

https://docs.microsoft.com/en-US/microsoft-365/bookings/turn-bookings-on-or-off?view=o365-worldwide#block-sharing-staff-details-with-customers

"Block Sharing Staff details with customers" is a highly requests feature within our user base.
However, the documentation provides 0 info as to what is actually meant with this.

The feature is enabled in our UAT environment.
When I schedule a booking with a gmail user on our MS Bookings test calendar, staff details are 100% sent directly over email.

The full display name containing First + Lastname is visible during the booking and send via mail.
Additionally, in the confirmation email, the email account of the Staff member is shown in the CC field of the email that is send to the customer.

These 2 little facts make me think that enabling the feature as global administrator, is not making any real changes.

Full name & email account are very private data.
In our specific case our company is a telecom company, the MS bookings app is used for video chat regarding sales.
Users that have made a bookings now send friend invites on social media to our staff (harasement) and get email send directly to them.

So either the feature is not working as intented, or the documentation is incomplete.

Please investigate.

Best regards

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba164b8e-a574-0744-ce02-23bda994e505
* Version Independent ID: 05018469-d6f8-0eb5-956c-730991912f8b
* Content: [Turn Microsoft Bookings on or off](https://docs.microsoft.com/en-US/microsoft-365/bookings/turn-bookings-on-or-off?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/turn-bookings-on-or-off.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/turn-bookings-on-or-off.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment] 2022-03-25 05:23
@QuintenPXS Thank you for your feedback. I'm currently testing this feature and will provide you an update shortly.

**Comment by msbemba** [comment] 2022-03-31 09:18
@QuintenPXS Thank you for your feedback. I was able to test and find that this is by design. The name and email will be shared with the customer and only the phone number is not. You can still request a design change via our main feedback portal - https://feedbackportal.microsoft.com/ . One of our Dev/product engineers will look it and provide an update.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment] 2022-03-31 13:09
@QuintenPXS Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Closed by yogkumgit** 2022-03-31 13:09 UTC
Labels: Bookings, product-feedback
