### ISSUE TITLE
Policy Tip shown for rule with no policy tip

### ISSUE THREAD

**Issue by jreyes4949** [MicrosoftDocs/microsoft-365-docs#5572] opened 2021-07-07 21:18 UTC
We have a policy that alerts users and blocks access when 5 or PII is found, we have a low severity rule that covers 0-4. User alerts are not enabled in our 0-4 policy. when crafting an email with 5 or more unique instances of PII we get the policy tip as expected, but if we craft an email with 5 instances of 1 unique PII our users get the policy tip even though the policy it triggers is the low severity one.

Is my understanding that a DLP policy looks at unique counts and not instances when determining the sensitive info threshold? and if so, does the Outlook policy tips not honor that logic?

**Comment by msbemba** [comment] 2021-07-09 16:00
@jreyes4949 Thank you for your feedback. Could you please provide the Document that you are referring to, so we can investigate and update the information?

Thanks
Sri

**Comment by msbemba** [comment] 2021-07-12 14:09
@jreyes4949  Thank you for your feedback. You are correct  DLP policy looks at unique counts and not instances when determining the sensitive info threshold. Could you please provide the document that you are referring to so we can ensure it is up to date?

Thanks
Sri

**Comment by jreyes4949** [comment] 2021-07-13 16:26
I was in this article originally but not sure if that's the right place. https://docs.microsoft.com/en-us/office365/troubleshoot/data-loss-prevention/data-loss-prevention-policy-tips

essentially in my testing i'm finding that policy tips are appearing for duplicate instances of sensitive info types we check instead of just unique counts and requires users to report before being allowed to send the content. once they hit report they can send the message and if our DLP rule doesn't block it the message goes out as expected and if we do have a block action it blocks as expected. Seems the DLP Policy Tip in Outlook doesn't follow the rule of Unique vs Instance count.

**Comment by msbemba** [comment] 2021-07-15 18:12
@jreyes4949 Thank you for the response. I was not able to reproduce this in my test lab as the "5 unique" works. This could be a bug on the tenant or a widespread issue with a subset of tenants, so the best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 

After you work with Support, if you think there could be modifications done to the document, please let us know.

Thanks
Sri

**Comment by jreyes4949** [comment] 2021-07-15 18:16
5 unique works, but 5 instances of a single unique value also triggers the policy tips.

So for example we expect this to trigger policy tip:
A
B
C
D
E

But we’re also seeing this trigger a policy tip.
A
A
A
A
A

Hope that makes sense. I can open a ticket but I wonder if it’s just a logic bug across the board.

Thanks,
José Reyes
Information Security

From: Sriraman M S ***@***.***>
Date: Thursday, July 15, 2021 at 11:12 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Reyes, Jose ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Policy Tip shown for rule with no policy tip (#5572)

CAUTION: External Sender: <https://github.com/jreyes4949> ***@***.******@***.***>. Validate sender before clicking links/attachments.

________________________________
@jreyes4949 Thank you for the response. I was not able to reproduce this in my test lab as the "5 unique" works. This could be a bug on the tenant or a widespread issue with a subset of tenants, so the best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at Get support<https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide>.

After you work with Support, if you think there could be modifications done to the document, please let us know.

Thanks
Sri

**Comment by msbemba** [comment] 2021-07-16 09:18
@jreyes4949 Yes, I mean 5 unique works and 5 instances regardless of unique count does not trigger the tip. I'd recommend you contact Microsoft Support and if you feel there are changes required in the document post the support experience, let us know.

Thanks
Sri

**Comment by yogkumgit** [comment] 2021-07-26 07:24
@msbemba  Thank you very much for the contribution and sharing this explanation. @jreyes4949 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it as here, we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2021-07-26 07:24 UTC
Labels: compliance, support-request
