### ISSUE TITLE
@binford2k

### ISSUE THREAD

**Issue by B-starboy** [MicrosoftDocs/microsoft-365-docs#5727] opened 2021-07-25 15:13 UTC
@binford2k

_Originally posted by @B-starboy in https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4989#issuecomment-840969263_

**Comment by B-starboy** [comment] 2021-07-25 15:14
Justifying my internet security system and the information I have had to go on is my only issue with the project.

**Comment by denisebmsft** [comment] 2021-07-26 13:51
Hello @B-starboy! Does this issue also apply to this article? https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-with-puppet?view=o365-worldwide

**Comment by B-starboy** [comment] 2021-08-03 18:47
I am not sure what you’re saying about this article and how it applies to the issue?

**Comment by denisebmsft** [comment] 2021-08-06 16:57
@yogkumgit @B-starboy 

There's another issue that was opened, and it said this:

It would be far easier to instruct users to puppet module install a module or add it to their Puppetfile than to laboriously walk them through creating a manifest to deploy. And it comes with the benefit that the user can just update the module when you make changes to it!

**Comment by yogkumgit** [comment] 2021-08-09 12:54
@B-starboy As this is a duplicate of #4989 . We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2021-08-09 12:55 UTC
Labels: duplicate
