### ISSUE TITLE
Add ability to set increments based on the top of the hour and the 30 minute mark

### ISSUE THREAD

**Issue by mimikantor** [MicrosoftDocs/microsoft-365-docs#5586] opened 2021-07-08 22:12 UTC
I have bookings set to display meetings in 30 minute increments with no buffer. Someone else has put a meeting on my calendar that ends at 10:25 which then throws off the rest of the meetings until the next one that ends at 1:30. In this image you see the 10:25 and then each 30 minute period is off by 5 minutes until it's reset based on my calendar. This isn't what I want to have happen. I want people to choose the start of the meeting at the top of the hour or the 30 minutes mark. 
![image](https://user-images.githubusercontent.com/35269613/124996963-db1e5580-e017-11eb-98f6-1b6eb39d9664.png)
<img width="184" alt="booking_minutes" src="https://user-images.githubusercontent.com/35269613/124997031-f5583380-e017-11eb-8eb9-fcd0fab0e685.png">

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07dc8679-b516-3935-85f2-4d849de28905
* Version Independent ID: 02c5529f-28fd-ad68-0b3b-e3b3fb72cc97
* Content: [Set buffer time in Microsoft Bookings](https://docs.microsoft.com/en-us/microsoft-365/bookings/set-buffer-time?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/bookings/set-buffer-time.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/set-buffer-time.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment] 2021-07-11 18:15
@mimikantor Thank you for your feedback. Since you have 30 minutes increments with no buffer then it would start showing options from 10:25. The best way is to update the meeting to 30 minutes instead of 25 so that the rest of the slots show up as expected.

Hope this helps!

Thanks
Sri

**Comment by mimikantor** [comment] 2021-07-11 18:52
It’s not my meeting so I can’t update it. I was invited it to it. Seems like a use case worth looking at for you. Many people schedule their meetings to have 5 minutes left at the end.


Mimi Kantor | she/her(s)

Digital Project Manager, Customer Experience | Mass.gov<http://mass.gov/>

1 Ashburton Place, 8th Floor, Boston, MA 02108<x-apple-data-detectors://1/0>

Cell: (646) 554-9965<tel:(646)%20554-9965> | Find me on Teams | Schedule a Meeting<https://calendly.com/mimi-kantor-mass-digital/meet-with-me>

***@***.******@***.***> |  www.mass.gov/eotss<http://www.mass.gov/anf/research-and-tech/oversight-agencies/itd/>

Executive Office of Technology Services & Security

We provide secure and quality digital information, services, and tools
to constituents and service providers when and where they need them.

________________________________

**Comment by msbemba** [comment] 2021-07-13 14:08
@mimikantor Thank you for your response. I'll test this in the lab and provide an update.

**Comment by msbemba** [comment] 2021-07-16 09:25
@mimikantor Thank you for your feedback. I was able to reproduce the issue, so it looks like it is by design since you have 30 minutes increments with no buffer. 

 We handle the documentation part and if you feel there are modifications required in this document, we will be glad to make those changes. But this is more of a support/Design request to Microsoft and The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide).

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment] 2021-07-16 16:31
@mimikantor Thank you for the response. You are right, we handle the documentation part, so Support would be the best point of contact for bugs or for configuration help.

Thanks
Sri

**Comment by yogkumgit** [comment] 2021-07-19 05:22
@msbemba  Thank you very much for the contribution and sharing this explanation. @mimikantor Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it as here, we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2021-07-19 05:22 UTC
Labels: Bookings, support-request
