### ISSUE TITLE
Error running Migration scripts

### ISSUE THREAD

**Issue by jermwormza** [MicrosoftDocs/microsoft-365-docs#2990] opened 2020-09-28 08:35 UTC
[Enter feedback here]
When Running either script the following error is displayed, is there a prerequisite that was missed as neither the New-OrganizationRelationship or the Set-OrganizationRelationship commands appear to have this parameter. If I edit and replace with MailboxMoveDirection then a similar error relating to the OAuthApplicationId parameter is shown on the Resource side. 

A parameter cannot be found that matches parameter name 'MailboxMoveCapability'.
    + CategoryInfo          : InvalidArgument: (:) [New-OrganizationRelationship], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-OrganizationRelationship
    + PSComputerName        : outlook.office365.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment] 2020-09-29 23:14
@jermwormza Thank you for your feedback. I tested this and see all parameters that the script uses for set-organizationrelationship are available currently. I found that the document https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationrelationship?view=exchange-ps is not up to date with all new parameters, But the parameters like mailboxmovecapability and mailboxmovepublishedscopes are working. Could you please provide screenshots of what exactly you see while running the script so that we can fix the document? This is a preview version and we really appreciate your feedback in helping us fix this

Thanks
Sri

**Comment by jermwormza** [comment] 2020-09-30 05:06
Hi Sri,

Thanks for your response, If I had not tested it so many times in the last
2 days I would think I was going mad, but just now when I was trying to
recreate the issue in order to obtain screenshots it is working and the
New-OrganizationRelationshipand the New-MigrationEndpoint now appear to
have the new parameters available.

Any idea what might have happened? Perhaps a delayed rollout or activation
of the new features to my tenants?

Jeremy Pointer
jermwormza@gmail.com

**Comment by jermwormza** [comment] 2020-09-30 05:20
Hi again,

looks like I spoke too soon, the parameters are on my target tenant
powermite.onmicrosoft.com but not on my resource tenant
bearingsintl.onmicrosoft.com

This is the error I'm getting
[image: Screenshot 2020-09-30 at 07.14.06.png]


Jeremy Pointer
jermwormza@gmail.com

**Comment by msbemba** [comment] 2020-09-30 19:59
@jermwormza Thank you for your feedback. The Preview version is available on all tenants and the tenant administrators in both source and target tenants can move mailboxes between the tenants. This could more of a support-related since you don't see it only on one tenant. I'd recommend you to contact Support via the need help option in the M365 admin center to see if this can be fixed from the backend.

Thanks
Sri

**Comment by jermwormza** [comment] 2020-10-01 04:44
Hi Sri,

The authors of the preparation scripts have also responded (text in yellow
block) on the following thread:
https://github.com/microsoft/cross-tenant/issues/10.
This  seems to confirm my suspicion that it is indeed a case of the build
version on the tenants which I have since confirmed (are/were) different, I
haven't checked again this morning yet.

[image: image.png]
Regards

Jeremy Pointer
jermwormza@gmail.com

**Comment by msbemba** [comment] 2020-10-01 11:05
@jermwormza Thank you for the update. Looks like this will be fixed in the next build in the coming weeks. Once again thank you for this valuable Feedback. 

@yogkumgit  There are no changes required on the document as this is a build issue confirmed by PG and they are fixing it. Please close this issue.

Thanks
Sri

**Comment by yogkumgit** [comment] 2020-10-02 12:21
@msbemba Thank you very much for the contribution and sharing this explanation. @jermwormza Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-10-02 12:21 UTC
Labels: enterprise

**Comment by xaven15** [comment] 2020-10-28 13:23
So I am having an issue with the first script: setupcrosstenantrelationshipfortargettenant

I believe I have the correct parameters in but obviously something isnt quite right.  I get all the way to the actual creation of the migration endpoint and the following occurs:
![image](https://user-images.githubusercontent.com/73595396/97441455-2451cd80-18ff-11eb-8d4c-cffea2603dac.png)

Thoughts or suggestions on what I am missing on my inputs??

**Comment by xaven15** [comment] 2020-10-28 13:45
Nevermind above.  I figured it out.  Was actually powershell connected to the resource when running the script for target domain.

**Comment by jermwormza** [comment] 2020-10-28 13:47
> 
> 
> So I am having an issue with the first script: setupcrosstenantrelationshipfortargettenant
> 
> I believe I have the correct parameters in but obviously something isnt quite right. I get all the way to the actual creation of the migration endpoint and the following occurs:
> ![image](https://user-images.githubusercontent.com/73595396/97441455-2451cd80-18ff-11eb-8d4c-cffea2603dac.png)
> 
> Thoughts or suggestions on what I am missing on my inputs??

Based purely on the grammar of error message I'm thinking you have specified the same tenant as both source(resource) and target (accessing). Just my 2c worth.
