### ISSUE TITLE
Broken Template Report

### ISSUE THREAD

**Issue by TamlinStryk** [MicrosoftDocs/microsoft-365-docs#4056] opened 2021-02-03 16:00 UTC
Hello, it appears that the provided template report has a calendar set to end on 12/31/2020, now that we've moved past that date some visuals of the report are broken.  When trying to extend the date of the calendar I get an error that it's causing "A circular dependency" to be created in the TenantMailboxUsage table.  Has anyone found a solution to this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a146d3a-b3d6-8993-e7f6-1b9da59f4ced
* Version Independent ID: 71a7043f-adcf-42d7-1c4b-670306a764f7
* Content: [Customize the reports in Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/customize-reports?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/customize-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/customize-reports.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by TamlinStryk** [comment] 2021-02-03 19:54
To follow up on this I believe I've discovered a potential solution to the root cause of this issue.

If the DAX that is used to create the calendar is replaced with the following:

Calendar = CALENDAR(DATE((YEAR(NOW())-2),1,1),DATE((YEAR(NOW())+2),1,1))

It should create a floating calendar that updates as time moves forward.

Unfortunately I am still stuck as attempting to modify or delete the current Calendar table results in the error above.

Thanks.

**Comment by TamlinStryk** [comment] 2021-02-09 03:43
I've found a work around to get this template working again, if you remove the "TotalIssueWarningQuota(KB/MB/GB/TB)" and "StorageUsed(KB/MB/GB/TB)" columns in the TenantMailboxUsage table you can then edit the calendar expression to extend the calendar.  

I would suggest replacing it with something like:

Calendar = CALENDAR(DATE((YEAR(NOW())-2),1,1),DATE((YEAR(NOW())+2),1,1))

in order to prevent something like this from happening in the future.

**Comment by yogkumgit** [comment] 2021-02-17 08:09
@Sirkkuw  Please add your comment and help us in resolving this issue. Thanks.

**Comment by yogkumgit** [comment] 2021-02-17 08:15
@scotvidican

**Comment by SKjerland** [comment] 2021-02-17 23:43
@yogkumgit - Sirkkuw is no longer at Microsoft and we haven't reassigned her articles yet. Scot asked me to help with this. The issue isn't with the article itself--it's with the Power BI template file that resides in the Download center. I have no knowledge of this Power BI template file and I have no idea who owns it. I'm going to have to do some investigating to figure out who can fix this. Please sit tight until I know more.

**Comment by SKjerland** [comment] 2021-02-19 02:40
@TamlinStryk - The Power BI team just uploaded an updated version of the template file to the Download center to fix this issue. Thanks for bringing it to our attention.

**Closed by SKjerland** 2021-02-19 02:40 UTC
Labels: admin
