### ISSUE TITLE
SharePoint Admins & Published Site Sensitivity Labels

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/microsoft-365-docs#6254] opened 2021-09-03 13:29 UTC
After doing some tests in multiple tenants, it seems that the SharePoint Site Labels that are published do not respect the Label Policy scope that pushes them out. After speaking with a SME on the topic, it was determined that this is by design, however this documentation does not call it out specifically.

Can this document be updated to include a callout that any Site Label that is created is able to be set onto a Site by SPO admins? This seems to be the only workload that doesn't respect the Label Policy scope for published labels.

This has been tested in 2x GCC tenants and 1x Commercial tenant - same behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#how-to-apply-sensitivity-labels-to-containers)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by SanjoyanM** [comment] 2021-09-03 22:59
@SeanTGeoghegan: SharePoint service works as following:

1. User mode: So when a user (including admin user) goes to create a site from SharePoint home page then he/she can see only the labels published to him. 

2. Admin Mode: When the same Admin user goes to SPO admin portal and tries to create a site from there then he/she can see ALL labels in the Organization. This is by design as SPO admin can create a site for some one else's behalf. If we show here a reduced list of labels then admin needs to be added to ALL the labels so that all lables are available to him.

Hope this makes sense.

**Comment by yogkumgit** [comment] 2021-09-10 10:56
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment] 2021-09-10 19:17
@SeanTGeoghegan  Can you confirm the answer is because you were using the SharePoint admin center, rather than an end user app?

**Comment by cabailey** [comment] 2021-09-11 01:09
We added the following clarification, does this cover it?

When you use admin centers that support sensitivity labels, you see all sensitivity labels for your tenant. In comparison, user apps and services that filter sensitivity labels according to publishing policies can result in you seeing a subset of those labels.

**Comment by SeanTGeoghegan** [comment] 2021-09-11 01:17
Hi Carol, sorry for the late response, yes that covers our question - they
were seeing differing behavior between SPO and Teams admin centers.

Thank you

Sean G
***@***.***

**Comment by cabailey** [comment] 2021-09-11 03:09
Great, pleased this covers it - closing this issue, Thanks for confirming, Sean!

**Closed by cabailey** 2021-09-11 03:09 UTC
Labels: compliance, writer-input-required
