### ISSUE TITLE
http://spamlink.contoso.com

### ISSUE THREAD

**Issue by cybernerd2014** [MicrosoftDocs/microsoft-365-docs#12830] opened 2023-09-21 04:22 UTC
<http://spamlink.contoso.com> is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a27041e-26ec-eaf9-83e3-a7a926a50d33
* Version Independent ID: 3a27041e-26ec-eaf9-83e3-a7a926a50d33
* Content: [Set up Safe Links policies in Microsoft Defender for Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links-policies-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-links-policies-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links-policies-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2023-10-16 20:35
@cybernerd2014, if the issue is still going on, you should open a support ticket.

**Comment by yogkumgit** [comment] 2023-10-17 11:14
@cybernerd2014 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2023-10-17 11:14 UTC
Labels: Defender for Office 365, support-request
