### ISSUE TITLE
Localized version is missing screenshots (de-de)

### ISSUE THREAD

**Issue by diecknet** [MicrosoftDocs/microsoft-365-docs#938] opened 2019-12-16 09:03 UTC
The localized version "de-de" is missing the screenshots 3-12. The files are online though. They are just not embedded properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae5f811-9551-ea95-b113-9175a6f08d7e
* Version Independent ID: e1eb8d3d-d439-e814-4a05-aa5bbc11f33e
* Content: [Overview of records - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/records)
* Content Source: [microsoft-365/compliance/records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/records.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by mypil** [comment] 2019-12-17 03:48
@diecknet - Thank you for pointing this out.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment] 2019-12-17 03:50
@tinamcN - Can you please assist with this Translation/Localization issue?


Thank you.

cc: @kenwith

**Comment by TinaMcN** [comment] 2019-12-17 19:31
@diecknet thank you for reporting this.   @OfficeGlobal please investigate and fix asap.  The issue is occurring in all languages so it may be an issue in the source?

**Comment by OfficeGlobal** [comment] 2019-12-18 07:05
@TinaMcN we have checked the source file, it has a same notation as INTL pages.
![image](https://user-images.githubusercontent.com/47977325/71063017-24742f00-216c-11ea-98d2-5d6ec978d7cb.png)

@cabailey could you please update images notation in the article to !\[AltText\]\(image path / name\) ?
Once updated the source we will update the INTL

at the moment notation with \:\:\: is processed as a plain text via iCMS and therefore it's visible at live site instead of images

**Comment by TinaMcN** [comment] 2019-12-18 17:05
The issue is fixed in the source file and published so the localized files should pick up the changes soon.

**Comment by robmazz** [comment] 2019-12-18 17:09
Closing - fixed published

**Closed by robmazz** 2019-12-18 17:09 UTC
Labels: compliance
