### ISSUE TITLE
Download link no longer works.

### ISSUE THREAD

**Issue by korggy** [MicrosoftDocs/microsoft-365-docs#5450] opened 2021-06-25 18:42 UTC
Download link no longer works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d71dab-a58d-fbd9-c30f-14f5884f094e
* Version Independent ID: 13e0112c-213d-b462-7833-9d0fe30fc99c
* Content: [Install and use the Junk Email Reporting add-in for Microsoft Outlook - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/junk-email-reporting-add-in-for-microsoft-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/junk-email-reporting-add-in-for-microsoft-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/junk-email-reporting-add-in-for-microsoft-outlook.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by siosulli** [comment] 2021-06-28 10:50
This looks to be a duplicate of 
https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5262 

If not, please re-open with more details! 

Thanks,
Sinead

**Closed by siosulli** 2021-06-28 10:50 UTC
