### ISSUE TITLE
Web Protection Profile steps are not valid

### ISSUE THREAD

**Issue by aaronnavratil** [MicrosoftDocs/microsoft-365-docs#8297] opened 2022-04-12 22:49 UTC
The page directs the creation of a new "Web protection profile" in MEM; but this profile type is not available

"
Go to the Microsoft Endpoint Manager admin center (https://endpoint.microsoft.com/), and sign in.
Choose Endpoint security > Attack surface reduction, and then choose + Create policy.
Select a platform, such as Windows 10 and later, select the Web protection profile, and then choose Create.
"

Please advise on the proper way to create a web protection profile, and update documentation.

See attached image:

<img width="1761" alt="asr" src="https://user-images.githubusercontent.com/64109888/163067169-02c993a8-9ed0-4c03-822c-85cdbf25eb62.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e228a0-6a2c-2ae2-655b-ada8b6f313bc
* Version Independent ID: fe0dcf35-c7f7-8dce-f829-9bc03827a40a
* Content: [Onboarding using Microsoft Endpoint Manager](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboarding-endpoint-manager?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboarding-endpoint-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboarding-endpoint-manager.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment] 2022-04-16 00:45
@aaronnavratil Thank you for your feedback. I tested this in a couple of tenants and was not able to reproduce the issue as I see the options mentioned in the document.

![image](https://user-images.githubusercontent.com/45987684/163655276-cb25975c-8805-4958-aa57-7f5d05672e11.png)

I'd recommend you to contact Microsoft support via the need help option on the admin center to file a bug or fix the problem with your M365 tenant.

Hope this helps!

Thanks
Sri

**Comment by aaronnavratil** [comment] 2022-04-16 16:45
Yes - it appears my tenant was lagged behind the documentation, the options are there now. I was not aware there were variability between tenants.....

**Comment by yogkumgit** [comment] 2022-04-17 14:36
@msbemba Thank you very much for the contribution and sharing this explanation. @aaronnavratil Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2022-04-17 14:36 UTC
Labels: Defender for Endpoint, doc-enhancement
