### ISSUE TITLE
Old demo

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#3080] opened 2020-10-06 16:42 UTC
The left side navigation contains a link to "Watch an extended overview of customizing DLP" that points to https://go.microsoft.com/fwlink/?linkid=852306 which is 3 years old. Can this be updated to something more current?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9616c17-a6cb-3b45-dbc6-07b4932bf7c7
* Version Independent ID: 4cb4c135-d8ae-8d44-985d-297374aab6f1
* Content: [Microsoft Information Protection in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/protect-information?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/protect-information.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/protect-information.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment] 2020-10-06 17:01
Not sure exactly where in the TOC this is but the issue is not with this page, so assigning to @chrfox

**Comment by DeanGross** [comment] 2020-10-07 11:55
It is in the Sensitive Information section of the TOC

**Comment by cabailey** [comment] 2020-10-08 15:23
The issue is not with this page, but n the Sensitive Information Type documentation, so assigning to @chrfox

**Comment by chrfox** [comment] 2020-10-20 21:56
@DeanGross 
This will be removed soon

**Closed by chrfox** 2020-10-20 21:56 UTC
Labels: compliance
