### ISSUE TITLE
SPO sites for O365 Groups are NOT included in "All SharePoint Sites" retention policy

### ISSUE THREAD

**Issue by Jvasil** [MicrosoftDocs/microsoft-365-docs#1021] opened 2020-01-07 17:45 UTC
In testing in brand new E5 test tenant I noticed that SPO sites for O365 Groups are NOT included in a retention policy that is applied to "All" "SharePoint Sites"..
 I don't recall that being the case previously and can't find anything documented on this being the expected behavior. 

The Office 365 Groups section of this article (see link below) needs to be updated to include this behavior just as it does for Exchange Mailboxes.. 
https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies#office-365-groups-locations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies#feedback)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment] 2020-01-07 18:27
@Jvasil  Thanks for your feedback!  Investigating.

**Comment by cabailey** [comment] 2020-01-15 19:17
@Jvasil  Thanks for your feedback.  The engineering team is looking into whether this is by design (in which case we'll document it as a limitation) or an issue to be fixed (in which case, nothing needs documenting).

**Comment by adelaidecopland** [comment] 2020-01-16 03:18
interested in the outcome of this, will be pushing out retention policies soon across O365 and want to be sure SPO site for Groups have appropriate coverage

**Comment by westerdaled** [comment] 2020-01-20 13:45
Here too.  I guess it would be consistent since the Outlook location doesn't include the group mailboxes.

**Comment by mypil** [comment] 2020-02-09 17:45
@Jvasil @adelaidecopland @westerdaled - From our understanding, the issue you raised has been answered by the author cabailey so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Closed by mypil** 2020-02-09 17:45 UTC
Labels: compliance

**Comment by adelaidecopland** [comment] 2020-02-09 21:40
@mypil so is it by design or an issue? @cabailey response only tells us that it is being looked into, not the outcome. We've pushed retention policy out to groups and it's not working on group sites

**Comment by Jvasil** [comment] 2020-02-10 15:15
@mypil the article needs to be updated with the proper information. 

There needs to be a statement under the "O365 groups location" section that states 
"Even though an Office 365 group has a SharePoint Online site collection, a retention policy that is set to include "All" SharePoint sites will not include sites that belong to an Office 365 group.

**Comment by cabailey** [comment] 2020-02-10 16:27
@mypil & @adelaidecopland :  I am still waiting confirmation from engineering whether this is by design or will be changed in the near future, and will update this thread accordingly.

**Comment by cabailey** [comment] 2020-02-21 23:42
@adelaidecopland  Now confirmed by design: "All SharePoint locations only applies to communication sites"

Now I have that confirmation, I'll update the documentation. Thank you for your patience, I know it's been a long wait.

**Comment by Jvasil** [comment] 2020-02-24 14:40
I don’t agree with "All SharePoint locations only applies to communication sites"..  that statement is not correct as there are other sites in SPO, besides just Communication sites, that are not O365 group connected such as Modern team sites that are not group connected and classic sites.. these types of sites also fall under the “All SharePoint locations” setting because they are not O365 group connected sites either..

Joe

**Comment by cabailey** [comment] 2020-03-02 16:56
Right - the initial response was based on the two main options in SharePoint Online site creation - communication site and Team site backed by an Office O365 group. But you can create two more types: Team site without an Office 365 group, and classic (legacy) site. These count as non-group sites as well.

**Comment by cabailey** [comment] 2020-03-10 22:46
Now clarified with this section: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies?view=o365-worldwide#sharepoint-locations

**Comment by Jvasil** [comment] 2020-03-11 14:17
Looks good! Thanks for your help on getting this clarified in our documentation!

Joe Vasil
Sr. Premier Field Engineer
Office 365 - SharePoint Online
US PFE - East Region
Office: +1 (980) 776-7488
jvasil@microsoft.com<mailto:jvasil@microsoft.com>
[MSFT_logo]
