### ISSUE TITLE
Error "4029:Multiple notification settings layout payloads" when deploying Defender for endpoint config to iOS

### ISSUE THREAD

**Issue by Kvikku** [MicrosoftDocs/microsoft-365-docs#5311] opened 2021-06-14 11:21 UTC
I get the following error when deploying the Defender for endpoint config profile to iOS devices

4029:Multiple notification settings layout payloads

And the devices do not appear in Security center as onboarded devices.

Thoughts/help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9d7718e-f707-9e4d-8583-4a6385b9b40c
* Version Independent ID: e5abdc8e-1b61-ca7c-d73c-b4d9d3a6de48
* Content: [App-based deployment for Microsoft Defender for Endpoint on iOS](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/ios-install.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-install.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment] 2021-06-17 13:08
@Kvikku Thank you for your feedback. I could not reproduce this issue, so this is most likely not a bug or a common issue, moreover this section of this repository is intended for product documentation only.

The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment] 2021-06-21 06:05
@msbemba  Thank you very much for the contribution and sharing this explanation. @Kvikku Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it as here, we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2021-06-21 06:05 UTC
Labels: Defender for Endpoint
