### ISSUE TITLE
SmarkScreen link for testing Network Protection doesn't get blocked

### ISSUE THREAD

**Issue by over2under3** [MicrosoftDocs/microsoft-365-docs#8819] opened 2022-06-07 04:00 UTC
[Enter feedback here]
I went through the steps to enabled Network Protection and the link (https://smartscreentestratings2.net/) used to confirm Network Protections is functioning correctly is not blocked. This link is blocked with SmartScreen but not network proection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c453008-4ccc-186c-b6da-64536d62c89c
* Version Independent ID: a00180f1-4f69-956f-cd92-77b7bf21fc16
* Content: [Evaluate network protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/evaluate-network-protection?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/defender-endpoint/evaluate-network-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/evaluate-network-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment] 2022-06-08 15:49
@yogkumgit , i tried on google chrome 32bit browser, i  received the following.


![Screenshot 2022-06-08 211844](https://user-images.githubusercontent.com/3296790/172661026-a1c9ea6a-16ed-4fce-bdcf-39091b89195f.jpg)

**Comment by msbemba** [comment] 2022-06-09 12:08
@over2under3 Thank you for your feedback. I was able to replicate the issue aswell. But this is not by design and needs to be reported to Microsoft support via the need help section in the admin center so that the engineer can raise a product bug and fix this in the backend.

Hope this helps!

Thanks
Sri

**Comment by over2under3** [comment] 2022-06-09 17:50
Did you implement this using GPO or Intune? I used GPO and still can't get this to work using Edge.

**Comment by yogkumgit** [comment] 2022-06-10 08:43
@msbemba Thank you very much for the contribution and sharing this explanation. @over2under3 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2022-06-10 08:43 UTC
Labels: Microsoft submitter, Defender for Endpoint, support-request
