### ISSUE TITLE
Request for correction of typographical error when reading in Japanese

### ISSUE THREAD

**Issue by kahosoka** [MicrosoftDocs/microsoft-365-docs#6064] opened 2021-08-18 04:46 UTC
[Enter feedback here]
Hello Team,

MDE on Linux repository configuration needs to be modified.
When I checked the item for specifying the channel in Ubuntu, "config" which was originally included in the path, disappeared on the Japanese site.

-------------------------------
excerpt from an English article
-------------------------------
Note your distribution and version, and identify the closest entry (by major, then minor) for it under https://packages.microsoft.com/config/ [distro] /.

In the below command, replace [distro] and [version] with the information you've identified:
curl -o microsoft.list https://packages.microsoft.com/config/[distro]/[version]/[channel] .list

For example, if you are running Ubuntu 18.04 and wish to deploy Microsoft Defender for Endpoint on Linux from the prod channel:

curl -o microsoft.list https://packages.microsoft.com/config/ubuntu/18.04/prod.list

https://docs.microsoft.com/ja-jp/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide#ubuntu-and-debian-systems

-------------------------------
excerpt from an Japanese article
-------------------------------
配布とバージョンに注意し、その下の最も近いエントリ (メジャー、マイナー) を識別します https://packages.microsoft.com/[distro]/ 。

次のコマンドで 、[distro] と [version] を、特定した情報に置き換える必要があります。
curl -o microsoft.list https://packages.microsoft.com/[distro]/[version]/[channel].list

たとえば、Ubuntu 18.04 を実行し 、Prod チャネルから Linux 上の Microsoft Defender for Endpoint を展開する場合は、次のようにします。
curl -o microsoft.list https://packages.microsoft.com/ubuntu/18.04/prod.list

I checked the relevant repository.
"prod.list" is stored under the result "https://packages.microsoft.com/config/ubuntu/18.04/".
From the above, you can see that the path of the Japanese site is wrong.
Therefore, we would like you to revise it.

Best Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab0b894-0199-7515-b060-a6724e2c9b9e
* Version Independent ID: 988ff83c-c4b5-d2f3-023e-2d8dd191b7ae
* Content: [Deploy Microsoft Defender for Endpoint on Linux manually](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide#ubuntu-and-debian-systems)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-manually.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-manually.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment] 2021-08-18 14:38
Hi @TinaMcN! Can you please take a look at this? Thank you!

**Comment by TinaMcN** [comment] 2021-08-18 18:44
@kahosoka thank you for reporting the issue.  The Japanese article is machine translated which is probably causing the problem.  I sent it for human translation, hopefully that will fix it.  It should be completed within a week.

**Comment by TinaMcN** [comment] 2021-09-24 22:31
@kahosoka the article has been human translated now.  Can you please check if the issue is fixed ok now?
https://docs.microsoft.com/ja-jp/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide#ubuntu-and-debian-systems 
You may close this issue if it's fixed.  Thanks again for reporting the problem.

**Closed** 2021-10-11 07:07 UTC
Labels: Defender for Endpoint, loc-bug
