### ISSUE TITLE
How do I report a message as Spam without opening the message and reading pane is off

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/microsoft-365-docs#10331] opened 2022-11-21 15:32 UTC
The report button is greyed out if reading pane is off, 
How do I report a message as Spam without opening the message and reading pane is off
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message or the Report Phishing add-ins - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment] 2022-11-28 04:29
@msbemba

**Comment by msbemba** [comment] 2022-11-29 13:11
@robinpoulose1 Thank you for your feedback. I tested it with multiple accounts and this is by design. If you would like to have a change in the way it works(design change), I'd recommend you provide feedback directly on our main feedback portal ( https://feedbackportal.microsoft.com/ ). Our dev and product team reviews the feedback and will be able to provide you more information. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment] 2022-11-30 12:51
@robinpoulose1 Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Closed by yogkumgit** 2022-11-30 12:51 UTC
Labels: Defender for Office 365, product-feedback
