### ISSUE TITLE
What Protocols can Access an In-Place Archive

### ISSUE THREAD

**Issue by bcihak** [MicrosoftDocs/microsoft-365-docs#6751] opened 2021-11-01 15:58 UTC
[Enter feedback here]
Can a section be added to clearly define what Clients and/or Protocols can access an In-place archive.  Would also like to know which Client/Protocols would allow access or even syncing of the In-Place Archive to occur if at all. 

Also what are the security ramifications or risk to data if un an unauthorized user were to access an M365 account that had an In-Place Archive enabled to that archived data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f19511c-5a0f-9d5f-0779-79a9ad99938f
* Version Independent ID: 3b513017-641c-38ae-3938-03a9ee3a6923
* Content: [Enable archive mailboxes in the Microsoft 365 compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-archive-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-archive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-archive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by bcihak** [comment] 2021-12-03 17:28
Hello,

Any update on an ETA?

Thanks!

**Comment by cabailey** [comment] 2022-10-24 18:30
We've had a change of writer since this was assigned with the writer-input-required label, but seems to be duplicate of https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6754, so closing.

**Closed by cabailey** 2022-10-24 18:30 UTC
Labels: compliance, writer-input-required
