### ISSUE TITLE
Activity Explorer does not show sensitivity label changes for office apps

### ISSUE THREAD

**Issue by technonath** [MicrosoftDocs/microsoft-365-docs#7038] opened 2021-12-01 13:08 UTC
Your documentation states:-
Sensitivity label activities and Retention labeling activities from Office native applications, Azure Information Protection add-in, SharePoint Online, Exchange Online (sensitivity labels only) 

But in my testing only updates done through sharepoint and the web apps show up, not if you edit them with the office apps - however if I check the Unified event log in powershell - they are captured there !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3d3633-893d-9354-9402-c47ed7dec790
* Version Independent ID: fc12340b-403f-b531-04be-91f00a8f0af6
* Content: [Get started with activity explorer - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-activity-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-classification-activity-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-activity-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment] 2021-12-14 06:39
@technonath Thank you for your feedback. I'm currently testing this to see if this is a bug in your tenant or by design.  I'll update you shortly.

Thanks
Sri

**Comment by technonath** [comment] 2021-12-14 07:52
Thank you, just to be clear it was when editing the office documents from
the same sharepoint location that has been synchronized with onedrive.

**Comment by yogkumgit** [comment] 2021-12-20 04:59
@chrfox Please help us in resolving this issue. Thanks/ Email sent with details: 12-19-2021

**Comment by chrfox** [comment] 2022-01-05 00:13
Hi @technonath , thanks for your comment. I have sent an inquiry to the product team. I'll update the content if necessary.  In the meantime, I suggest that you open a Support ticket.

**Closed by chrfox** 2022-01-05 00:13 UTC
Labels: compliance, writer-input-required
