### ISSUE TITLE
Typo in PowerShell example

### ISSUE THREAD

**Issue by Sherd21** [MicrosoftDocs/microsoft-365-docs#4611] opened 2021-04-05 20:04 UTC
Section "[Use PowerShell to apply a sensitivity label to multiple sites](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#use-powershell-to-apply-a-sensitivity-label-to-multiple-sites)" 
Step 5: Run the following command to apply the label to these sites. Using our examples:

There is a typo in the PowerShell example.

instead of:
> $sites | ForEach-Object {**Set-SPOTenant** $_.url -SensitivityLabel $Id}

it should be:
> $sites | ForEach-Object {**Set-SPOSite** $_.url -SensitivityLabel $Id}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#how-to-enable-sensitivity-labels-for-containers-and-synchronize-labels)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment] 2021-04-05 20:54
@Sherd21 Are you saying you tried the command as documented, and it didn't work?

**Comment by Sherd21** [comment] 2021-04-05 21:03
No, it didn't. The different command should be used, Set-SPOTenant. It even specified under code example in a next sentence: To apply different labels to different sites, repeat the following command for each site: **Set-SPOSite** -Identity <URL> -SensitivityLabel "<labelguid>"

**Comment by cabailey** [comment] 2021-04-05 21:40
If it's not working as documented, please open a support ticket for investigation.  I'm told the command as documented should be used to apply a sensitivity label across multiple sites in your tenant (no need to specify the site), and to use Set-SPOSite only if you need to apply different sensitivity labels to different sites (so need to specify the site).

**Comment by SanjoyanM** [comment] 2021-04-16 17:15
@Sherd21 this syntax should work perfectly and is correct. I believe the "set-spotenant" may be confusing but its by design --> $sites | ForEach-Object {Set-SPOTenant $_.url -SensitivityLabel $Id}

After running it if you face specific error message let us know and open a ticket. Our engineers will do an investigation.

**Comment by yogkumgit** [comment] 2021-04-22 12:13
@SanjoyanM Thank you very much sharing this explanation. @Sherd21 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2021-04-22 12:13 UTC
Labels: compliance

**Comment by Sherd21** [comment] 2021-04-22 16:22
thank you for explanation and apologize for slow response. I had some problems with running the cmdlets but they were due to slow replication of labels in my tenant.
I think confusion on my side was related to Set-SPOTenant cmdlet usually used to set global/tenant settings where Set-SPOSite is to set settings for individual site.  Thank you
