### ISSUE TITLE
Change text in teams app when group creation has been disabled.

### ISSUE THREAD

**Issue by JohanssonMarkus** [MicrosoftDocs/microsoft-365-docs#2827] opened 2020-09-14 11:08 UTC
When disable the M365 group creation. The label in Teams app. is still "Join or create a team"
It must be changed to "Join a team" right? 
![image](https://user-images.githubusercontent.com/32453241/93078692-39dea100-f68b-11ea-9b13-86e814f3dd46.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445c0a2e-1a22-d90f-0c73-0edf34f2b99a
* Version Independent ID: d534ac69-134d-0198-fcb9-e19d1ed44d4b
* Content: [Manage who can create Microsoft 365 Groups](https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment] 2020-09-17 06:26
@JohanssonMarkus Thank you for your feedback. When you click on it does it allow you to create a team in spite of disabling group creation? 

Thanks
Sri

**Comment by JohanssonMarkus** [comment] 2020-09-17 12:20
No it's not possible to create M365 group. But it's very confusing for our users to believe they can. But we have disabled it tenant wide.

**Comment by msbemba** [comment] 2020-09-17 18:48
@JohanssonMarkus Thank you for the feedback. I tested it and it is by design that it shows up Create or join a Team, but when they click on it the next page only has the option to Join. There is nothing much we can do with the documentation, however, this is already been added to the UserVoice section and our Engineering team is working on it to fix this.

LInk to user voice:- 
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/35791423-disable-the-join-or-create-a-team-button-in-the


@yogkumgit  There are no changes in the documentation. Please close this issue.

Thanks
Sri

**Comment by yogkumgit** [comment] 2020-09-18 06:39
@msbemba Thank you very much for the contribution and sharing this explanation. @JohanssonMarkus Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-09-18 06:39 UTC
Labels: solutions

**Comment by dharcrow** [comment] 2020-09-22 19:07
Just a quick question and this is due to my very basic PowerShell knowledge. When I copied and pasted the PowerShell command code to specify a security group to not be able to create groups, I initially made a mistake. On the first line: $GroupName = "<SecurityGroupName>" I accidentally included the brackets <>. My group name was "cannotaddgroups" but I put <"cannotaddgroups">. As a result it seemed to turn off group creation for everyone in the org. I went back and fixed it by undoing what I had done in the code, but I wanted to make sure that the issue was syntax and the brackets basically selected all groups whereas if I had done it correctly with "cannotaddgroups" it would have specified to that exact security group that I had made? Thank you for any guidance.

**Comment by msbemba** [comment] 2020-09-22 20:33
@dharcrow That is correct. The brackets should not be added. Since you ran it with an incorrect group, the value of GroupCreationAllowedGroupId would have been empty, which means it blocks the entire organization as the EnableGroupcreation Value is set to False. So it is important to run (Get-AzureADDirectorySetting -Id $settingsObjectID).Values after the script to find out if the below two are stamped correctly.

![image](https://user-images.githubusercontent.com/45987684/93934541-f0541d00-fd40-11ea-9ecf-732e1bc408a0.png)

Hope this helps!

Thanks
Sri

**Comment by dharcrow** [comment] 2020-09-22 22:01
Outstanding! Thank you very much.

**Comment by dharcrow** [comment] 2020-09-23 13:39
I was wondering if you could help me with one detail. It appears that in this code I am creating a group that can only create groups and the rest of the organization cannot. I am hoping to do the opposite. I am a tech coordinator for a K-12 school and all students and staff are using Teams. We are having trouble with the younger kids in elementary creating Teams that can sometimes be a little exclusive and mean to other students, which is why I want to shut off groups to some students. I have students grouped in Office 365 by graduation year, so I am hoping to shut off groups/teams creation to only a few grade levels and leave it open to everyone else (older students) including teachers. Is this possible using the coding above but doing a slight tweak? Again, many thanks for all your guidance.

**Comment by msbemba** [comment] 2020-09-24 18:42
@dharcrow Thank you for the question. While this is more of a support question, I'll still try to answer to the best of my knowledge. However, the support team can provide the best possible resolution for this.

* Nest all groups that you would like to allow to this main security group which is allowed to create m365 groups. Note that this works only if all of the groups are mail enable security groups.

Thanks
Sri
