### ISSUE TITLE
Testing sensitive info types

### ISSUE THREAD

**Issue by MrsGMark2** [MicrosoftDocs/microsoft-365-docs#3505] opened 2020-11-19 14:15 UTC
https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type?view=o365-worldwide#test-custom-sensitive-information-types-in-the-security--compliance-center

The above document suggests there should be a way to test manually created sensitive information types, however the option to do this isn't actually there. I've looked in the Compliance portal and the option is unavailable.
What happened to this feature?

Thanks
---

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb7953e-5257-2578-4607-2d93940d6845
* Version Independent ID: 8e59d041-619e-d54f-f28e-faac2bc18ef2
* Content: [Create a custom sensitive information type in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-a-custom-sensitive-information-type.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-custom-sensitive-information-type.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment] 2020-11-26 09:37
@chrfox  Please add your comment and help us in resolving this issue. Thanks.

**Comment by chrfox** [comment] 2020-12-16 23:17
Hi @MrsGMark2 
That feature is still there.  I am unable to reproduce your experience. You should contact Microsoft Support Services to resolve your issue.

**Closed by chrfox** 2020-12-16 23:17 UTC
Labels: compliance
