### ISSUE TITLE
Zero documentation on PowerShell cmdlets for this

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/microsoft-365-docs#10181] opened 2022-11-08 18:02 UTC
Can we get some documentation on:
Get-ReportSubmissionPolicy
Get-ReportSubmissionRule

Had a customer in GCC recently find their UI was broken and that there was ZERO powershell guidance.  This is really needed, especially when a single UI change (add a reporting mailbox) touches this many settings:

![image](https://user-images.githubusercontent.com/10875667/200641156-43f254fb-7908-4ba1-8295-f564b1d8cd81.png)

Please provide some articles on these cmdlets and usage!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e53205b5-8850-42b6-0b0c-8a61b7ef7776
* Version Independent ID: 0a9e7903-ce3c-e877-e6b3-b45d09642308
* Content: [User-reported email settings for spam, phish, as malicious mail - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/user-submission?view=o365-worldwide#:~:text=Delivering%20user%20reported%20messages%20to%20a%20custom%20mailbox,were%20formerly%20known%20as%20the%20User%20submissions%20policy)
* Content Source: [microsoft-365/security/office-365-security/user-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/user-submission.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2022-11-08 20:59
@chrislehr, the state of the feature and cmdlets is in flux. I had PowerShell content complete and published back in late July, but I was soon asked to remove it. You can see what it looked like [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/d3d307fa1559ea18320af678502f8705cfe758ae/microsoft-365/security/office-365-security/user-submission.md#use-exchange-online-powershell-to-configure-the-user-submissions-mailbox-for-email).

But, it's unclear to me at this point if the information is still the same, or if the changes have already started.

**Comment by rorylee1986** [comment] 2022-12-06 16:59
@chrislehr @chrisda Is this a known issue with the GCC admin portal GUI for the User reported settings? I get a 503 error every time I try to save changes on the web GUI. I was eventually able to enable the User reported settings via the "unpublished" PowerShell commands posted above, however it concerns me a bit considering it's "unpublished"? Is there a reason why it's not published to the public? Will there be any issues if I use the PowerShell commands vs the GUI?

**Comment by chrisda** [comment] 2022-12-06 17:32
@rorylee1986, the changes are being rolled out as we speak, which might be the cause of your issues. The changes are described in MC466195 and MC455512. I'm feverishly working to get the updates published; it's taking longer than anticipated. After I'm finished with that, I'll get to work on the updated PowerShell procedures.

**Comment by chrisda** [comment] 2023-01-10 23:29
Topic update with PowerShell instructions 1/10/2023.

Thanks for the feedback.

Closing.

**Closed by chrisda** 2023-01-10 23:29 UTC
Labels: Defender for Office 365

**Comment by chrislehr** [comment] 2023-01-11 00:11
Thank you team!  😄


________________________________
