### ISSUE TITLE
Archive delete tag doesn't work per Microsoft support?

### ISSUE THREAD

**Issue by SeaGT** [MicrosoftDocs/microsoft-365-docs#11259] opened 2023-03-07 18:23 UTC
Email in our archive mailboxes is not being deleted after 4 yrs, even though we have an archive delete tag in our policy, have manually run the ManagedFolderAssistant multiple times, and don't have any in-place holds. Opened a case with Microsoft Support and am being told that email in an archive mailbox will never get deleted even if the tag is applied. Shouldn't this info be included in this page discussing retention policy?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81e9c1f9-d22d-8c83-25bb-637f3121ef33
* Version Independent ID: b6c1f57d-978f-c959-ef0a-00ef1b9d9cab
* Content: [Customize an archive and deletion policy (MRM) for mailboxes - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment] 2023-03-07 19:18
@SeaGT  This isn't my understanding ("email in an archive mailbox will never get deleted even if the tag is applied") & also checked with engineering.  Please ask your support engineer to contact me.

**Comment by cabailey** [comment] 2023-03-15 19:50
This is not a confirmed doc issue, closing.  If updates are identified after the support engineer contacts me, I'll process that internally.

**Closed by cabailey** 2023-03-15 19:50 UTC
Labels: compliance

**Comment by SeaGT** [comment] 2023-03-15 20:52
Hi Carol,

I appreciate you following up on this issue, thanks for your time.  I would disagree that this is not a doc issue - the Microsoft docs are unclear and so I see a lot of people struggling with record retention in Exchange and getting emails to delete automatically.  I posted my issue in several different Outlook forums and got many workaround suggestions - including running multiple rules on a regular basis, PowerShell scripts to delete emails, auto archive suggestions, etc. Why not just add an example in your docs of how to use retention tags to move email into archive mailboxes and then how Microsoft recommends the emails be deleted from the archive mailbox after a given time?

And provide a similar example of how to do this in the new self-expanding archive?  And explain why users can't delete emails from the self-expanded archive?

These simple examples would have saved me so many hours of time + your support engineer's time.  Thanks

Greg
***@***.******@***.***>
Desk: 206.576.6012 | IT Support: 206.576.6013
"A pessimist sees the difficulty in every opportunity, an optimist sees the opportunity in every difficulty" Winston Churchill

**Comment by cabailey** [comment] 2023-03-20 19:20
@SeaGT  We have documentation how to move emails to the archive mailbox (https://learn.microsoft.com/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes) using MRM retention tags and we have documentation how to delete emails after a specified time using M365 retention (https://learn.microsoft.com/microsoft-365/compliance/create-retention-policies&tabs=other-retention#create-and-configure-a-retention-policy). 

I don't have confirmation from the engineering team that owns the features that the retention tag will prevent deletion (my understanding of what you're saying).  I can't update the documentation from anecdotal reports, because it could be a bug that needs fixing (or misconfiguration or missed prereqs).  I will look into this if the support engineer who gave you this statement contacts me, but I have yet to hear from anybody to get the details.

I also haven't heard of users not being able to delete emails from their auto-expanding archive mailboxes. Do you have a support ticket for this separate issue?  We document users can't delete the folders, and the Recover Deleted Items feature isn't supported, but we specifically document "Users can delete items in an auto-expanded storage area": https://learn.microsoft.com/microsoft-365/compliance/autoexpanding-archiving#outlook-requirements-for-accessing-items-in-an-auto-expanded-archive

**Comment by SeaGT** [comment] 2023-03-20 21:15
Hi Carol,

Thanks for following up.
I agree that you’ve got those 2 on articles retention (I’ve been through them multiple times😉), what I’m asking for is an additional paragraph in there that tells the reader that the archive mailbox will NOT have items deleted from it unless you use one of these options:

  1.  use a Purview deletion policy (the solution I used)
  2.  create Outlook rules and run them on the Archive mailbox
  3.  use the Outlook AutoArchive function
  4.  create a personal tag and apply that to the archive mailbox (this is untested – it was suggested by the support engineer Jameson but not confirmed / Jameson is CC’d on this email)
A paragraph along these lines would save so much time and stress for your users.

For the auto-expanding archive mailbox issue, I was reading this:
If an archive mailbox has at least one auto-expanded storage area, users can't delete a folder from the archive mailbox or from the auxiliary archive. In other words, after an auto-expanded storage area has been provisioned, they can't delete any folders in the archive.
                Learn about auto-expanding archiving - Microsoft Purview (compliance) | Microsoft Learn<https://learn.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide#outlook-requirements-for-accessing-items-in-an-auto-expanded-archive>

You’re correct about deleting emails (I think, but I haven’t play with the AEAM feature yet).  In the same Learn article, it mentions search being trickier in AEAM and that some folder numbers may be incorrect – so we’re not going to try AEAM until Version 2 is out.
Again, thanks for your time.

Greg
***@***.******@***.***>
Desk: 206.576.6012 | IT Support: 206.576.6013
“A pessimist sees the difficulty in every opportunity, an optimist sees the opportunity in every difficulty” Winston Churchill

**Comment by cabailey** [comment] 2023-03-23 19:57
@SeaGT I do not see the need for a doc update, here. Right at the beginning of the article we cover this very point:

"To retain and delete emails, we recommend you use Microsoft 365 retention policies and retention labels] rather than the older messaging records management (MRM) from Exchange Online. However, a valid reason to still use this older feature is to automatically move emails from a user's primary mailbox to their archive mailbox. You might also need to use MRM to apply retention and deletion settings to specific folders in the mailbox, rather than the entire mailbox.

Use this article as an example deployment for these two valid reasons to use MRM retention policies and retention tags. For all other retention and deletion scenarios, use Microsoft 365 retention policies and retention labels."

Although other methods might work to delete the emails, we always recommend M365 retention policies/labels & keep MRM tags for just the 2 purposes documented.  This guidance is consistently repeated in other places, for example https://learn.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#use-retention-policies-and-retention-labels-instead-of-older-features and the Note at the top of the MRM documentation such as the one on https://learn.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#use-retention-policies-and-retention-labels-instead-of-older-features
