### ISSUE TITLE
Information on Teams users with hybrid mailboxes is incorrect

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#4576] opened 2021-03-31 09:54 UTC
The following paragraph needs to be updates as users with a Exchange hybrid with on premises mailboxes now get a Exchange online mailbox allocated just fort her storage of the eDiscovery Teams chat, meeting and call records. See page with details  https://docs.microsoft.com/en-us/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users?view=o365-worldwide

Important
In a cloud-based organization, users who participate in conversations that are part of the chat list in Teams must have an Exchange Online mailbox in order to retain chat conversations when the mailbox is placed on an eDiscovery hold. That's because conversations that are part of the chat list are stored in the cloud-based mailboxes of the chat participants. If a chat participant doesn't have an Exchange Online mailbox, you won't be able to preserve those chat conversations. For example, in an Exchange hybrid deployment, users with an on-premises mailbox may be able to participate in conversations that are part of the chat list in Teams. But in this case, content from these conversation can't be preserved because these users don't have a cloud-based mailboxes that can be placed on hold. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7263ba97-4e79-7144-a9d4-5138fe228fa2
* Version Independent ID: 316e242e-7f37-592e-9c8f-e754b23a29ca
* Content: [Create eDiscovery holds in a Core eDiscovery case - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-ediscovery-holds?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-ediscovery-holds.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-ediscovery-holds.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment] 2021-03-31 17:46
Hi @nikki-c  isn't this issue a duplicate of https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4488? If so, I'm going to close issue 4488. Regardless, I will update this note as per your request (so that it aligns with topic on searching for teams chats for on-premises users.

**Comment by markjjo** [comment] 2021-04-02 19:01
@nikki-c FYI that the note in this article has been updated.

**Closed by markjjo** 2021-04-02 19:01 UTC
Labels: compliance
