### ISSUE TITLE
DLP Disclaimer Exclusion

### ISSUE THREAD

**Issue by suriyanarayanangk** [MicrosoftDocs/microsoft-365-docs#5272] opened 2021-06-10 08:11 UTC
Hi there,

I created a DLP Custom Rule Pack to identify the below keywords by the DLP Policy.
 

- Internal Use
- Confidential
- Client Confidential
- Restricted

I want to exclude my organization disclaimer in the custom DLP Policy for that purpose I have created the below code but it is not working fine.

 <Any  maxMatches="0" minMatches="0">
        <Match idRef="Organization_Disclaimer"/>
 </Any>

I have the data classification that contains the word **Confidential** I want to trigger the DLP Policy when it matches the data classification.

But we have an organization disclaimer so I want to exclude that, otherwise, all the emails will detect by the DLP Policy they may result in a false positive.

So please help me to achieve my goal.

Thanks in Advance.

**Comment by suriyanarayanangk** [comment] 2021-06-10 08:18
`<Any  maxMatches="0" minMatches="0">
        <Match idRef="Organization_Disclaimer"/>
  </Any>`

**Comment by msbemba** [comment] 2021-06-15 13:01
@suriyanarayanangk Thank you for your feedback. The customer DLP Rule structure needs to evaluated to troubleshoot and advise next steps or find out the root cause as to why it is not working. The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 

Thanks
Sri

**Comment by suriyanarayanangk** [comment] 2021-06-15 13:17
Thank you so much @msbemba for your assistance.

I already reached out to them and I didn't get solutions for my issue.

**Comment by msbemba** [comment] 2021-06-15 13:29
@suriyanarayanangk Thank you for your response. This Channel is specifically created for Documentation updates and we do not troubleshoot issues. I'd recommend you to try contacting support again as that's the right channel.

Thanks
Sri

**Comment by suriyanarayanangk** [comment] 2021-06-15 13:32
Hi Sri,

Thank you so much.

I will try to contact the support again.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yogkumgit** [comment] 2021-06-16 07:03
@msbemba  Thank you very much for the contribution and sharing this explanation. @suriyanarayanangk Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it as here, we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2021-06-16 07:03 UTC
Labels: compliance

**Comment by suriyanarayanangk** [comment] 2021-06-16 07:08
Hi @msbemba,

I want to know whether the code that I used for the exclusion of content is correct or not.

I am sharing the link for your reference.

https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell?view=o365-worldwide

My actual motive is to exclude a Disclaimer part from the DLP Rule will be picked up.

Please help me with the syntax.
