### ISSUE TITLE
Limitations on Users and Groups

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/microsoft-365-docs#4104] opened 2021-02-09 15:32 UTC
This page needs a reference to the number of users and/or groups that can be included in a label policy.  It should also clarify whether nested groups can be used - e.g. members of a group reference in the label policy can be groups as well as users.  Any limit or constraint should be added e.g.  number of levels of nesting (depth), number of nested groups,  number of groups a user is a member of, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57908eea-077f-363c-8d51-3b8335914f4c
* Version Independent ID: 0d1421f1-b546-677f-ef3b-7e3da294b5ef
* Content: [Create and publish sensitivity labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-sensitivity-labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment] 2021-02-09 23:06
@bholzmmc If there were limits on the number of users and groups that could be included in a label policy, yes, this is where we would document that. However, there are no technical limits for either of these.  A while ago, I believe there was a problem with nested groups but that wasn't by design - it was a bug that's now fixed.  

I'm told label policies don't have technical limitations on the number of levels for nesting.  But as with all features that use nested groups, there's a potential performance issue if nesting levels go too deep.  With so many variables to factor in (Azure AD does the unpacking), I suspect this might be a case of trial and error for each environment.  Other than documenting "For the best performance, don't use nested groups" I'm not sure what prescriptive guidance we could document here and don't want to give the impression that nested groups won't work or will always be a problem. 

If you are experiencing problems with nested groups not working at all, please contact Support.  If you are experiencing problems only with heavily nested groups, try reducing the nesting level to find what works best in your environment.

**Comment by bholzmmc** [comment] 2021-02-10 17:18
Thank you Carol; I had a note from last year regarding the 200 entry limit in classic AIP and it was stated the same is true in UL (ref view it on GitHub<https://github.com/MicrosoftDocs/Azure-RMSDocs/issues/1189#issuecomment-644088534>).   I could not find any reference relating to the response  “scoped policy limit applies for unified labeling. I'll adjust the page so it is more clear in the next version we publish” from that thread.  Did that limitation exist and was removed or was the original respondent incorrect ?

Brian

**Comment by cabailey** [comment] 2021-02-12 01:58
Looking into this statement from the AIP side - it's not clear to me from the documented statement whether this limit was enforced or just a support statement but policies for AIP labels are on a different platform to sensitivity labels that you see in the Microsoft 365 compliance center. I can see how the phrase "unified labeling" might be ambiguous in this context.  After you activate unified labeling, the classic client uses label policies that you see in the Azure portal and the unified labeling client uses label policies that you see in the compliance center.  But the labels are the same.

**Closed** 2021-02-12 13:15 UTC
Labels: compliance

**Comment by bholzmmc** [comment] 2021-02-12 13:17
Thanks Cabailey.
