### ISSUE TITLE
Customer Lockbox details

### ISSUE THREAD

**Issue by fl0mb** [MicrosoftDocs/microsoft-365-docs#4729] opened 2021-04-19 09:06 UTC
Does Customer Lock-box also work for other Microsoft Services like Teams? Description is inaccurate.
Or does Teams data reside in OneDrive/Exchange/Sharepoint ?

https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-lockbox-requests.md

**Comment by msbemba** [comment] 2021-04-22 04:00
@fl0mb Thank you for your feedback. Customer Lockbox supports requests to access data in Exchange Online, SharePoint Online, and OneDrive when Microsoft engineers need to access customer content to determine the root cause and fix an issue. It is not available for MS Teams yet.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment] 2021-04-26 12:16
@msbemba Thank you very much for the contribution and sharing this explanation. @fl0mb Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2021-05-05 13:52 UTC
Labels: compliance
