### ISSUE TITLE
Not overly helpful

### ISSUE THREAD

**Issue by mwilliams7247** [MicrosoftDocs/microsoft-365-docs#8087] opened 2022-03-22 21:19 UTC
To start the document states one needs to go to off board section of endpoint and basically follow the steps/options. There is a note that it will take 7 days to show up as clients are off boarded. 

This is not helpful as I am looking to move from Defender for Endpoint P2 -> Defender for Business and I am being told this is a required step. So there is no way to speed this up or just make a simple change? I have to guess that all the devices are removed and wait 7 days to find out? Or go one by one to see that the Off Board Script ran... or the Off Board Script had errors with no more information. 

It would seam to me there is a serious disconnect in this process and much better documentation can be provided for these steps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d52e56ae-7d90-fe14-2d04-99a12b5653d9
* Version Independent ID: 321c630e-3f0b-9213-593a-4bb9a394aad9
* Content: [Offboard devices from the Microsoft Defender for Endpoint service](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/offboard-machines?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/offboard-machines.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/offboard-machines.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment] 2022-03-31 08:23
@mwilliams7247 Thank you for your feedback. You are correct, The status of a device will be switched to inactive 7 days after offboarding. This is the information we have received and it is by design. However, I understand your situation and I think the support team might be able to speed up the process in the backend. I'd recommend you contact the support team and sort this out. Meanwhile, after working with support, if you feel the document can still be improved, let us know.


Support team can be contacted via the need help section on the admin center.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment] 2022-03-31 12:55
@msbemba Thank you very much for the contribution and sharing this explanation. @mwilliams7247 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2022-03-31 12:55 UTC
Labels: Defender for Endpoint, support-request
