### ISSUE TITLE
Live Response limitations

### ISSUE THREAD

**Issue by povlhp** [MicrosoftDocs/microsoft-365-docs#11521] opened 2023-03-30 10:06 UTC
Live esponse limitation are supposedly as below - Yet,  I am hitting a limit currently, that is not listed:

Here is my status - and I can't run any more live response 
I do pause 6s between calls. I have 0 running sessions. So why can't I submit more liv response commands ? 

```
 $status = callurl -url "https://api.securitycenter.microsoft.com/api/machineactions" -token $dtoken ; $z= $status.content| ConvertFrom-Json ; $y= $z.value ; $y.status | group-object

Count Name                      Group
----- ----                      -----
    7 Failed                    {Failed, Failed, Failed, Failed…}
   26 Pending                   {Pending, Pending, Pending, Pending…}
  136 Succeeded                 {Succeeded, Succeeded, Succeeded, Succeeded…}
    6 TimeOut                   {TimeOut, TimeOut, TimeOut, TimeOut…}

```

> Limitations
> Rate limitations for this API are 10 calls per minute (additional requests are responded with HTTP 429).
> 
> 25 concurrently running sessions (requests exceeding the throttling limit receives a "429 - Too many requests" response).
> 
> If the machine isn't available, the session is queued for up to three days.
> 
> RunScript command timeouts after 10 minutes.
> 
> Live response commands can't be queued up and can only be executed one at a time.
> 
> If the machine that you're trying to run this API call is in an RBAC device group that doesn't have an automated remediation level assigned to it, you need to at least enable the minimum Remediation Level for a given Device Group.
> 
>  Note
> 
> Device group creation is supported in Defender for Endpoint Plan 1 and Plan 2.
> 
> Multiple live response commands can be run on a single API call. However, when a live response command fails all the subsequent actions won't be executed.

**Comment by povlhp** [comment] 2023-03-30 12:25
Found out, if you have more than 25 in "Pending", no more requests are accepted.  You can send > 25 requests, and as long as you don't have >= 25 in status pending (you can have many in status progress), you can add more.  I have had luck addind about 50 live response actions per batch. Then wait 30 minutes, cancel all Pending, and add the next group. When done go back and try to reach those that I did not have success with the first time around (Status cancelled)

Too bad it is 25 and not minimum 25, and max 5-10% of computers. Limit is again designed for SOHO, and not Enterprise deployments. 5% of all devices would be more than enough in most cases.

**Comment by denisebmsft** [comment] 2023-03-30 16:54
Hello @povlhp. Can you please tell us to which article your feedback applies? This information will help us route the issue to the correct writer/team. Thank you!

**Comment by msbemba** [comment] 2023-04-03 08:05
@povlhp Thank you for your feedback. Looks like this is by design and the feedback to increase the limit would need to be directed to our dev/product group via the main feedback portal (https://feedbackportal.microsoft.com/)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment] 2023-04-04 10:36
@povlhp Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Closed** 2023-04-04 10:36 UTC
Labels: product-feedback
