### ISSUE TITLE
Information about chats not being retained for on premises users is incorrect

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#4488] opened 2021-03-20 21:50 UTC
The statement below is incorrect. 

> In a cloud-based organization, users who participate in conversations that are part of the chat list in Teams must have an Exchange Online mailbox in order to retain chat conversations when the mailbox is placed on an eDiscovery hold. That's because conversations that are part of the chat list are stored in the cloud-based mailboxes of the chat participants. If a chat participant doesn't have an Exchange Online mailbox, you won't be able to preserve those chat conversations. For example, in an Exchange hybrid deployment, users with an on-premises mailbox may be able to participate in conversations that are part of the chat list in Teams. But in this case, content from these conversation can't be preserved because these users don't have a cloud-based mailboxes that can be placed on hold.

Organisations with hybrid exchange have shadow Exchange online mailboxes created to hold copies of the chat compliance records. Historically you needed to ask Microsoft to enable this feature but now it is enabled by default. 

 The Add Office app content for on-premises users checkbox is added under the Locations in Content Search. This allows eDiscovery to search the chats for on premise users.

See Microsoft Doc article https://docs.microsoft.com/en-us/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users?view=o365-worldwide. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7263ba97-4e79-7144-a9d4-5138fe228fa2
* Version Independent ID: 316e242e-7f37-592e-9c8f-e754b23a29ca
* Content: [Create eDiscovery holds in a Core eDiscovery case - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-ediscovery-holds?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-ediscovery-holds.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-ediscovery-holds.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment] 2021-03-26 06:47
@nikki-c Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4535

Thanks
Sri

**Comment by markjjo** [comment] 2021-03-31 17:47
@nikki-c Closing this issue as dupe of https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4576 that you recently opened. I will also review/update PR#4535. The changes in the PR aren't quite accurate.

**Closed by markjjo** 2021-03-31 17:47 UTC
Labels: compliance
