### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by aingber** [MicrosoftDocs/microsoft-365-docs#8502] opened 2022-05-05 20:42 UTC
In the File Plan, the 'SubCategory' field also has a 64 character limit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4465ca1-9ee2-e551-aff2-9fc8e4a5eae3
* Version Independent ID: 2cbc9375-d055-edf8-0f89-b5794f7aa7a7
* Content: [Use file plan to manage retention labels - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/file-plan-manager?view=o365-worldwide#information-about-the-label-properties-for-import)
* Content Source: [microsoft-365/compliance/file-plan-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/file-plan-manager.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment] 2022-05-06 19:39
I'm checking if this is by design or a bug - seems a strange field to have this old limitation when it was removed for the others.

**Comment by cabailey** [comment] 2022-05-26 02:42
@aingber   This has been open a long time - not forgotten but engineering hasn't had time to look into this properly. It is not confirmed as by design so closing this GitHub Issue and I've filed a separate item for further investigation.  Thank you for your patience.

**Closed by cabailey** 2022-05-26 02:42 UTC
Labels: compliance

**Comment by sparkitect** [comment] 2022-06-15 22:49
It appears to be the same (64 char limit) for the CitationName column as well.

**Comment by cabailey** [comment] 2022-06-15 23:01
@sparkitect  Thanks for this feedback.  I've asked for all fields to be checked and confirm whether length restrictions are by design or a regression to be fixed.

**Comment by sparkitect** [comment] 2022-06-15 23:34
## Current Documentation
![image](https://user-images.githubusercontent.com/9206808/173958802-4437eafb-b079-4819-b51d-5f4df968eabe.png)

## Currently _Correct_ Documentation
![image](https://user-images.githubusercontent.com/9206808/173959128-427ee76b-2e0c-4c3c-9e52-01abc509be6a.png)

@cabailey I could submit a Pull Request with the documentation updated to match the current reality, as tested, assuming that it can be fixed again once you have the confirmation you're waiting for.

Or would a PR take longer to process that you expect to wait for said confirmation?

**Comment by cabailey** [comment] 2022-06-16 00:01
@sparkitect Please don't create a PR for this.  We document "by design" and not bugs, and as I've already explained, the engineering team hasn't confirmed whether this is a bug or by design and want to test all fields, not document exceptions piecemeal.  Thank you for your patience.

**Comment by sparkitect** [comment] 2022-06-16 02:01
@cabailey Ok, I will follow your lead.

As a Microsoft customer, I have no porblem looking for (or creating) Issues if things don't seem to work 'as documented'.

_However_, as a consultant, I've seen customers lose confidence in the software, and themselves, when things don't work out.
Many of them assume that the documentation describes what _**IS**_ rather than what **_should be_**.
As a result, expectations are unmet and they think _they_ did something wrong[^1]. 

[^1]: THAT I have a porblem with 🤓

**Comment by sparkitect** [comment] 2022-06-16 02:05
BTW, I realize this is out of your control and I truly appreciate you, your work, and the conversation :-)

**Comment by cabailey** [comment] 2022-06-17 00:36
@sparkitect Yes, I understand that point of view and if something doesn't work as documented, please do report it by following your standard support channels. People who have access to the code and have troubleshooting tools will be able to confirm whether it's a misconfiguration or not.  It's also easier to prioritize reported issues when we have customer support incidents whereas GitHub Issues are designed for the documentation. 

While I believe your reported experience, what I can't know, is whether this is the case for all customers, under all circumstances. For example, it might not be the case for another customer in another region or some other variable. What I do know, is that engineering made a change to remove the previous 64-character limit on all but the LabelName field, which is when this documentation was updated with the current information, and signed off by them. The PM owner requested this was investigated before changing the documentation. While it's frustrating to wait, I believe the error message is clear, so it's not blocking deployment.
