### ISSUE TITLE
Promote the tile to App Launcher

### ISSUE THREAD

**Issue by maramraghavendra** [MicrosoftDocs/microsoft-365-docs#2309] opened 2020-07-03 08:31 UTC
Promote the tile to App Launcher removed in new version so could you please remove this line in the KB.
https://docs.microsoft.com/en-us/microsoft-365/admin/manage/customize-the-app-launcher?view=o365-worldwide

PG team confirm on this option

**Comment by get-itips** [comment] 2020-07-22 12:26
Hello @maramraghavendra how are you?
I was able to promote the custom tile created to app launcher without issues. Can you specify what you mean with "new version" ?
Thank you

**Comment by maramraghavendra** [comment] 2020-07-23 02:36
Hi Andres,

I am good, thanks for asking!


According to the official document, there will be an option to pin to launcher. https://docs.microsoft.com/en-us/microsoft-365/admin/manage/customize-the-app-launcher?view=o365-worldwide<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fadmin%2Fmanage%2Fcustomize-the-app-launcher%3Fview%3Do365-worldwide&data=02%7C01%7Cragma%40microsoft.com%7C54525b786cbc48bf3be208d81f2715f7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637293600081773780&sdata=GsuOXrLJqyRO2t3uMohFmm88%2F8mDiUU6JzQagsR7Hdc%3D&reserved=0>
[cid:image001.png@01D660DB.8B789C50]


But Customer cannot see the option to pin apps to their user Shell UX anymore and confirm with PG team this is by design so could you please update this KB.

[cid:image002.png@01D660DB.8B789C50]

Regards,
Raghu

**Comment by get-itips** [comment] 2020-07-23 12:53
Hello @maramraghavendra 
I do have the pin to launcher option

![image](https://user-images.githubusercontent.com/36666927/88288426-21c15580-ccca-11ea-9dfd-96bff9be66e3.png)

But this is an action every user has to perform.

**Comment by maramraghavendra** [comment] 2020-07-24 02:11
I am not sure how you have this option, but I checked with more than 4-tenant don’t have same option so I raised bug to PG and confirm same.

[cid:image001.png@01D661A2.B888FD30]

Regards,
Raghu

**Comment by get-itips** [comment] 2020-07-24 19:23
> I am not sure how you have this option, but I checked with more than 4-tenant don’t have same option so I raised bug to PG and confirm same.

If you have communication with PG please ask is this is going to be removed soon.
I can not reproduce so I can not remove that information yet.
Thank you

**Comment by get-itips** [comment] 2020-07-27 14:32
Hello @maramraghavendra how are you? Could you get more information about this? As I said, I can not reproduce on several tenants, on my side. Thank you

**Comment by maramraghavendra** [comment] 2020-07-28 05:48
No I confirm with PG on this.(attached ICM)

Still I can see same error for new tenant so pls create new tenant and check again.

If you want I can share my test account to you.

https://icm.ad.msft.net/imp/v3/incidents/details/192694225/home

Regards,
Raghu

**Comment by get-itips** [comment] 2020-07-28 12:55
@twernermsft Tom, can you kindly step in and help us confirm if the functionality to promote a custom tile to app launcher has been or is next to be removed? 
I can not reproduce what @maramraghavendra kindly shares here, but he says he confirmed with PG.
I appreciate.

**Comment by maramraghavendra** [comment] 2020-07-29 05:38
@Allen Talidro (Shanghai Wicresoft Co,.Ltd.)<mailto:v-alltal@microsoft.com>: pls help me to share PSR.

Regards,
Raghu

**Comment by maramraghavendra** [comment] 2020-07-29 05:50
Hi Raghu,

The customer created a customer tile called "PitchBook" . It successfully shows in the landing page but when you click on ellipsis, there is no option to "Pin to launcher" . Please see screenshots below:
[cid:image001.png@01D665AE.422F7690]

[cid:image002.png@01D665AF.27680920]

As per this article, https://docs.microsoft.com/en-us/microsoft-365/admin/manage/customize-the-app-launcher?view=o365-worldwide We should be able to see "Pin to launcher."
[cid:image003.png@01D665AF.27680920]




Regards,
Allen
Office 365 Support Engineer

From: Raghavendra Rao Maram <ragma@microsoft.com>
Sent: Wednesday, July 29, 2020 1:39 PM
To: MicrosoftDocs/microsoft-365-docs <reply@reply.github.com>; MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>; Allen Talidro (Shanghai Wicresoft Co,.Ltd.) <v-alltal@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/microsoft-365-docs] Promote the tile to App Launcher (#2309)

@Allen Talidro (Shanghai Wicresoft Co,.Ltd.)<mailto:v-alltal@microsoft.com>: pls help me to share PSR.

Regards,
Raghu

**Comment by get-itips** [comment] 2020-08-03 17:25
Hello @maramraghavendra 
I could not reproduce on a newly created demo tenant. Let's see if we can get more information from @twernermsft
Thanks

**Comment by yogkumgit** [comment] 2020-08-04 06:21
@twernermsft please help us with your comments to resolve it. Please also let us know if the document update is required or not.

**Comment by lhcole** [comment] 2021-05-14 22:08
Because we haven't gotten an answer about this from the product team and this is months old, I'm closing this issue. Please reopen with updated comments and screenshots if this is still a problem and I'll shepherd the updates personally.

**Closed by lhcole** 2021-05-14 22:08 UTC
Labels: admin
