### ISSUE TITLE
Add Callout for Publishing Requirements between AAD/Teams/SPO

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/microsoft-365-docs#7563] opened 2022-01-31 20:12 UTC
I'd like to ask if there can be a callout for the current behavior of labels between M365 Groups/Teams/SharePoint Online.

Current behavior:

- SPO for Admins: Requires that a label exist and be scoped for Sites/Groups.
- SPO for Users, M365 Groups, and Teams: Requires that the label exist, be scoped for Sites/Groups, and be published to the users via Label Policy.

This may make sense to add after [this section:](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#apply-a-sensitivity-label-to-a-new-site)

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment] 2022-01-31 20:50
@SeanTGeoghegan  We have already documented that these labels must be scoped to sites & groups, and published for users to apply.  What you might be missing is the following sentence in the SharePoint admin center section (https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#view-and-manage-sensitivity-labels-in-the-sharepoint-admin-center):

"Unlike user apps, where sensitivity labels can be assigned to specific users, the admin center displays all sensitivity labels for your tenant."

If admins are applying them in apps, the labels still need to be published.

**Comment by SeanTGeoghegan** [comment] 2022-01-31 20:53
@cabailey you are right - I did miss that part! Thank you for the clarification.

**Comment by cabailey** [comment] 2022-01-31 21:43
Use the page's list of admin centers vs user apps - and which ones support sensitivity labels for sites & groups: https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#support-for-sensitivity-labels   For example, the Azure portal for group management lets you assign the labels as admins, Teams admin center doesn't yet support these labels.

**Comment by SeanTGeoghegan** [comment] 2022-01-31 22:52
Thank you for that,

The Azure AD M365 Group Management interface requires that Sensitivity Labels be published to the user creating the group, even though it is an admin center - any admin creating groups that does not have them published will not be shown the Sensitivity Drop down.

**Comment by cabailey** [comment] 2022-02-01 00:09
Thanks, let me check these with engineering.

**Comment by yogkumgit** [comment] 2022-03-15 06:34
@cabailey Awaiting your kind response. Thanks

**Comment by cabailey** [comment] 2022-03-15 15:56
Yes - not forgotten!  Support for the Teams admin center was confirmed by engineering & updated on the page. The anomaly for the Azure AD portal was the reason for the delay & still under discussion with engineering.  The expected design is that an admin would be able to see all the labels, but the Azure AD documentation does say "The current signed-in user must be within the scope of the sensitivity label publishing policy".  I wondered if this difference is because users who aren't admins can create and then manage Microsoft 365 groups in the Azure AD portal - so the portal here is acting more like a user app than an admin portal.

Since the Azure AD documentation has this requirement, I'm updating the page day today to reflect this but will need to update again if there's a change to allow admins to see all labels.

**Comment by cabailey** [comment] 2022-03-15 17:54
Doc update live now, so closing this issue.  But I will continue to look into this & revise as needed.

**Closed by cabailey** 2022-03-15 17:54 UTC
Labels: compliance
