### ISSUE TITLE
SharePoint Syntex - Managed Metadata entity extractor not populating values from Synonyms

### ISSUE THREAD

**Issue by vigneshvdm** [MicrosoftDocs/microsoft-365-docs#4085] opened 2021-02-08 07:18 UTC
I have created an extractor and added few labels

When the labels match the exact terms, the managed metadata column is getting populated. But when the label is defined as a synonym for a term in term store management, the column is not getting populated with the respective term. 

For instance, I have a term called Metal which has Iron, Silver defined as synonyms. When the document has the word Silver/Iron, it is not adding the term Metal.

The labels are getting extracted, I defined a similar extractor and mapped it to a single line of text column and Syntex added the value Iron/Silver to it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e87ae4b6-5ba5-4f94-94f7-d7a16a633e86
* Version Independent ID: 2486de11-2337-e1b7-3dbc-8fc94fd46e40
* Content: [Leverage term store taxonomy when creating an extractor](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/leverage-term-store-taxonomy)
* Content Source: [microsoft-365/contentunderstanding/leverage-term-store-taxonomy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/leverage-term-store-taxonomy.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by vigneshvdm** [comment] 2021-02-11 03:34
Do we have any update on this issue? Synonyms are used extensively used by the business and Syntex might not be the right product for automatically tagging documents if Syntex doesn't have the ability to recognize synonyms and add the relevant term

**Comment by efrene** [comment] 2021-02-11 16:33
Sorry for the delay in getting back to you, @vigneshvdm.  @seansquires, can you help on this?

**Comment by seansquires** [comment] 2021-02-12 17:53
Hi @vigneshvdm - your expectation is correct; sorry to hear that you've run into this issue. I confirmed that there was an authentication regression preventing the full taxonomy match (incl. synonyms) from occurring. This has since been resolved. Can you please confirm that you are still experiencing the issue? Thanks!

**Comment by vigneshvdm** [comment] 2021-02-12 19:57
Hello @seansquires, thank you for looking into this. 

I just tried adding a label that is defined as a synonym and Syntex is having some issues in recognizing that. 
When I add the label, it gives me an error "The content labeled does not match with the current column/extractor data type." 
And the documents that has this label, are not getting tagged with relevant term.

**Comment by vigneshvdm** [comment] 2021-02-16 18:31
Hello @seansquires 

Do we have an ETA for this? 

We are evaluating Syntex to replace BA insight's Autoclassifier in SharePoint online. Recognizing synonyms and adding relevant term is a critical component for us to achieve this. Please advice.

Regards,
Vicky

**Comment by seansquires** [comment] 2021-02-17 00:13
Hello @vigneshvdm - can you clarify what you mean when you say you are adding a synonym label? Is this in the training interface or in the library where a trained model has been applied? If you are in the model training experience you won't see synonym matches there; that only occurs when the file is uploaded and the model is processing the file.

**Comment by vigneshvdm** [comment] 2021-02-17 18:06
Hello @seansquires  , 

Let me explain with an example. Assume I have a term called Metals and it has 2 synonyms Iron, Silver defined in the term store. 

When the document has the word Metals, the managed metadata column gets tagged with Metals, but when the documents have words like Iron or Silver which are synonyms of Metals, the column is not getting populated. Hope that clarifies

Regards,
Vicky

**Comment by vigneshvdm** [comment] 2021-02-17 19:44
Hello @seansquires ,

From what I observed, a phrase is mandatory for Syntex to recognize the labels. 

For instance, if the labels Iron/Silver are always followed/preceded by some phrase, we can add that to explanations and Syntex will recognize the labels. But if we don't have such common phrases, Syntex is not be able to recognize the labels. 

In our case, we have more than 100,000 documents, we don't have a fixed format where we can say that the labels "Iron/Silver/Metals" are going to be around a phrase.
We are trying to achieve the following scenario, which I think is not possible with Syntex

`If the document has these words, "Iron", "Silver" or "Metals" extract them as labels. `

Please let me know your thoughts. 

Regards,
Vicky

**Comment by seansquires** [comment] 2021-02-19 07:08
Yes, in your example with Metals and synonyms Iron & Silver, if you train the model to identify that entity at runtime (when a file is uploaded to a library with that trained model applied) it will save to the MMS column field the preferred label if it matches on the label or it's synonyms. So if it extracts Metal from file 1, it writes Metal. If it extracts Iron - a synonym of Metal from file 2, it writes Metal. If it extracts Magnesium and there's no synonym or preferred label match, it will not save anything to the field. 

To your second reply, you observed correctly. Syntex doesn't do rules-based search; it does algorithmic entity extraction based on the labeling and explanations you provide so it knows where to look in the document for the entities you wish to extract. The phrases containing the entities don't have to be in the same place, but if there's no consistency in the phrase containing the desired entity so that you can teach the model with an explanation, then it will be difficult to train a model to reliably/consistently extract the value.

**Comment by vigneshvdm** [comment] 2021-02-19 17:33
Thank you @seansquires 

In one of my extractors, I tagged the label "Iron" and it was able to predict the label "Iron" in the training as well, the accuracy was 90%+ 

But when I upload the same document that I used in Training to the actual document library where the model is applied, it is not adding the value to the managed metadata column. Since it is identifying the label Iron in the Training, it should have added the "Metal" tag to the managed metadata column. 

Is there a way I can create some support ticket and have someone from your team look at what's going on? 

Regards,
Vicky

**Comment by yogkumgit** [comment] 2021-04-09 16:23
@seansquires Thank you very much for the contribution and sharing this explanation. @vigneshvdm Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2021-04-09 16:23 UTC
Labels: enterprise

**Comment by tomresing** [comment] 2021-09-21 20:31
@vigneshvdm you can [request support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide) the standard way. There's full support for SharePoint Syntex in that model.
