### ISSUE TITLE
Offboarding no longer works, psexec -s cmd.exe sc stop sense is detected as a threat by Defender

### ISSUE THREAD

**Issue by JonathanPitre** [MicrosoftDocs/microsoft-365-docs#10740] opened 2023-01-19 00:54 UTC
Couples questions and comments regarding this process.

1. The offboarding script no longer works as Defender itself detects the psexec command as a virus threat when trying to stop the sense service.
![image](https://user-images.githubusercontent.com/15003329/213330008-13793df8-9e0e-471d-9471-f5aba2f95bfd.png)
If the service cannot be stopped, the reg value senseGuid and the files from "C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Cyber" can't be deleted either.

2. Please provide an improved PowerShell script to do the offboarding that actually works and has been tested. Doing QA on a recommended script to guarantee that the actual Antivirus is working is kind of important. This needs to work 100%.

3. If indeed we need to download a fresh copy of the WindowsDefenderATPOnboardingScript.zip file every month, please provide a static URL to download it so we can automate the task with our master image update. Something like http://aka.ms/WindowsDefenderATPOnboardingScript. At this moment, this is a complete nightmare to maintain.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef5b23fe-37ce-e3b0-ad76-55a416eaa865
* Version Independent ID: 26becb70-47ff-38fe-592f-99d84f6aba12
* Content: [Onboard non-persistent virtual desktop infrastructure (VDI) devices](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-vdi?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-vdi.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-vdi.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by PehDeh** [comment] 2023-01-19 12:10
had the same issue, so i did take over permissions deleted it and then had issues onboarding it until i recreated the folder cyber as system again.(MDEAnalyzer showd a hint that the folder has to be recreated.)

**Comment by yogkumgit** [comment] 2023-01-22 04:25
@siosulli Please help us in resolving this issue. Thanks

**Comment by siosulli** [comment] 2023-01-23 12:29
Hi @yogkumgit  I have reached out to the PM and will revert here. Thanks!

**Comment by siosulli** [comment] 2023-01-24 11:50
Hi @JonathanPitre - thanks for opening this issue. I have confirmed with the PM and this should be opened as support ticket. 

For guidance on opening support tickets see:
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/contact-support?view=o365-worldwide
 
cc @yogkumgit 

Thanks,
Sinead

**Comment by JonathanPitre** [comment] 2023-01-24 14:56
look I already took the time from my busy schedule to report the flaws in the documentation. The least you guys can do is take it seriously and fix it. After all it's your product and it ain't free. Since I don't work for free, I'm not gonna waste more time on this.

**Comment by siosulli** [comment] 2023-01-24 15:20
Hi @JonathanPitre - your time and feedback is much appreciated - I have escalated this to the appropriate team and they are reviewing it. Once I have clarification from them I will be able to update the documentation. Thanks.

**Comment by AlexNuggz** [comment] 2023-02-01 11:00
@siosulli Any updates on this?

**Comment by siosulli** [comment] 2023-02-01 12:18
Hi @AlexNuggz I'm working on this with relevant team at the moment. We know why this is happening now and it's related to Tamper Protection being On. I'm just trying to understand if this is something that can be handled in the PowerShell script.

**Comment by AlexNuggz** [comment] 2023-02-01 12:32
Thanks @siosulli do you know if theres another way to achieve the same result? We're currently trying to deploy for our Citrix environment but can't find another way around this so that the Gold Image isn't onboarded.

**Comment by siosulli** [comment] 2023-02-02 09:22
Hi @AlexNuggz and @JonathanPitre and @PehDeh 

Would you mind confirming when you are running the script if you are logging in as local admin/or running the cmd prompt as local admin and then executing the offboarding .cmd file?

Thanks,
Sinead

**Comment by JonathanPitre** [comment] 2023-02-02 15:20
Can you please clarify if you are talking about the onboarding or the offboarding script?

The onboarding script is copied to C:\WINDOWS\System32\GroupPolicy\Machine\Scripts\Startup, therefore it's ran at next startup in the SYSTEM context since it's running as a machine startup script.

The offboarding script is ran with admin rights obviously and then psexec -s force the remaining commands to be ran under SYSTEM context. -s is for SYSTEM. The remaining commands are never executed anyways since Defender blocks their execution as explained above.

I don't know how to make this clearer.

**Comment by siosulli** [comment] 2023-02-02 20:26
Thanks, yes, I was just clarifying the script was being ran as per the documentation. Based on this and from investigations with the team the documentation should work as described.

This may be down to a configuration in the environment and as our support team would be best placed to investigate this side of things, at this point, if anyone is still blocked and needs further support they should follow up with them.

**Closed by siosulli** 2023-02-02 20:26 UTC
Labels: Defender for Endpoint, writer-input-required

**Comment by JonathanPitre** [comment] 2023-02-03 13:25
Unbelievable, many already confirmed they have the issue and I already provided all the evidence to show what's the root cause.

The issue is not fixed so why close it? Is it too much to ask that Microsoft provides accurate documentation and script tgat actually work on a paid product ?

This is highly unprofessional.

**Comment by BalintOberrauch** [comment] 2023-02-07 15:48
@siosulli Please update your documentation. Onboarding a master image to every MS Product is NOT needed and creates only issues which are (like in this case) a nightmare.

**Comment by JesseEsquivel** [comment] 2023-02-07 17:43
@JonathanPitre please provide your contact information.

**Comment by JonathanPitre** [comment] 2023-02-08 23:44
You can reach me on https://www.linkedin.com/in/jpitre/

**Comment by mpat777** [comment] 2023-04-06 19:32
Any update on this issue?

**Comment by serran0** [comment] 2023-10-09 13:29
Any updates? We have a situation where ASR policies are stuck and will not update no matter what product is used. Trying to clear them with PSexec of course fails due to "PSexec & WMI" policy is set to block.
