### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/microsoft-365-docs#6185] opened 2021-08-27 12:53 UTC
I have a client who reports that if they simulate an attack, and is his test, if the client forwards but does not open the e-mail (i.e. forward to the admin), the report indicates that that user is potentially compromised. Is that by design or a bug?

**Comment by msbemba** [comment] 2021-09-06 21:39
@Jmartinez589 Thank you for your feedback. I was able to reproduce the issue, this looks like this is by design as it says potentially compromised as a phish was delivered to the mailbox.

Hope this helps!

Thanks
Sri

**Comment by Jmartinez589** [comment] 2021-09-06 22:06
Thanks for the update. I was siding with 'by design' and your clarification helps.
________________________________

**Comment by yogkumgit** [comment] 2021-09-07 05:28
@msbemba Thank you very much for the contribution and sharing this explanation. @Jmartinez589 If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2021-09-07 05:28 UTC
Labels: Defender for Office 365, doc-enhancement
