### ISSUE TITLE
Block access of files on unmanaged devices takes precedence over the external sharing control in SharePoint

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/microsoft-365-docs#7744] opened 2022-02-17 19:22 UTC
Can you confirm that "block access of files on unmanaged devices" takes precedence over the external sharing control in SharePoint? I can find this documentation in zero locations. 

![image](https://user-images.githubusercontent.com/52167303/154555035-ed31cb5a-aa14-496d-abf1-2b5494c47863.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#more-information-about-the-dependencies-for-the-unmanaged-devices-option)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment] 2022-02-22 09:52
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment] 2022-03-04 02:14
According to the PM, these two settings are unrelated and different layers of protection. If a user is blocked by conditional access because of an unmanaged device, other site policies won't be relevant (can't access the site).  But the same user could switch to another device that is managed, the conditional access policy check is successful and then the sharing externally policy kicks in.

**Comment by HarrisburgUSysAdmin** [comment] 2022-03-04 13:08
So there is no way for our Human Resources team to share files or folders from their own Teams site since we are using the block access (conditional access / device policy)? 

This just doesn't sound right. 

Yes, we want to restrict access at the top level by restricting access to managed devices but there are many cases where HR needs to share out files with terminated employees or consultants.

What you are saying is this is not possible?

**Comment by cabailey** [comment] 2022-03-05 20:19
Since the PM has confirmed these settings work independently, no doc updates are needed & I'll close this GitHub Issue for the documentation.  If using this combination of settings doesn't work for your specific business requirements (you need to allow access to unmanaged devices), then don't use them. As you know, these settings are not unique to sensitivity labels but simply make them easier to apply to sites. For advice on configuring the specific settings to best meet your business requirements, consider bringing in Microsoft Consultancy Services with knowledge of conditional access policies and SharePoint site configuration.

**Closed by cabailey** 2022-03-05 20:19 UTC
Labels: compliance, writer-input-required

**Comment by cabailey** [comment] 2022-05-18 19:18
@yogkumgit  According to the PM, there is no doc enhancement needed here because these settings are independent, so removing that label.
