### ISSUE TITLE
Deleting Office 365 group | Guest user experience

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#6348] opened 2021-09-15 07:50 UTC
Hello,

Would be great to add documentation about deleting the Office 365 group and especially what will happen with Guest users that are members of this group and maybe Members of another group.
So as an example:

1. Guest user Andrew
2. User is a member of Group A
3. User is a member of Group B
4. We delete Group A
5. What will happen with the user account?

Asking because if remove a Guest user from Office 365 group, then user access to the tenant is "locked", user cannot access the tenant anymore, so the user must be added to any group again or re-invited. 
But what if we delete a group, this triggers the same process that the user is removed from the group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809bcea7-ebd6-58bc-9ff0-e764a459016d
* Version Independent ID: f86ecf79-7095-772a-980e-356a995061c5
* Content: [Overview of Microsoft 365 Groups for administrators - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/office-365-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/office-365-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment] 2021-10-06 13:53
@ArunMSFT can you comment?

**Comment by yogkumgit** [comment] 2021-12-02 08:20
@MikePlumleyMSFT and @arun-msft-zz second reminder. Thanks

**Comment by yogkumgit** [comment] 2022-01-09 06:26
@arun-msft-zz Please help. Thanks

**Comment by ArunMSFT** [comment] 2022-01-11 06:24
This is being discussed internally with Mike. We are not able to reproduce the problem. I would suggest raising a ticket with the respective product group via support. @MikePlumleyMSFT  is also a part of the discussions and can advise.

**Comment by yogkumgit** [comment] 2022-01-11 12:03
@lightupdifire Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Closed** 2022-01-11 12:03 UTC
Labels: admin, support-request, writer-input-required
