### ISSUE TITLE
Who can change the labels?

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/microsoft-365-docs#1278] opened 2020-02-24 12:48 UTC
In case of user-defined permissions, it is not clear which permission level role can change the label. In my tests, except Viewer all roles (Reviewer, Co-Author, Co-Owner) can change the label (configured to assign custom permissions) but protection is retained. Only co-owner can remove the protection which is expected. Could you please clarify this?
Additional Info: I got two label policies: 1. includes labels to all employees and has also a default label configured 2. Includes one additional label (encryption enabled) only to few users and the problem is with this label in 2nd policy. Highest priority is set for first policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dd3497a-c02a-5fd6-12db-3a093f0fe17c
* Version Independent ID: 2ef81556-61b0-47ae-d8fc-3d9aa5240c51
* Content: [Restrict access to content by using sensitivity labels to apply encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-sensitivity-labels#let-users-assign-permissions)
* Content Source: [microsoft-365/compliance/encryption-sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment] 2020-02-24 14:50
@prashant1380  Changing the existing encryption requires first removing the encryption.  So I would expect no difference in permissions between changing a label on a document that applied custom permissions to another label, and changing the same label to one that applies the Remove encryption action.  You need Save As, Export or Full Control to remove encryption, which is documented (https://docs.microsoft.com/en-us/azure/information-protection/configure-usage-rights#rights-included-in-permissions-levels) as included in Co-Owner only. If you're seeing a different result, I recommend opening a support ticket for investigation because there are too many variables to cover with GitHub Issues.  Make sure you include the version of the Azure Information Protection unified labeling client, and the exact steps for them to reproduce what you're seeing.

When you apply a label with encryption and user-defined permissions, and then change the label, it is expected that the original encryption is preserved if the new label doesn't apply encryption.  Was that your test when you said "protection is retained"?  That result is documented in this section https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-sensitivity-labels#what-happens-to-existing-encryption-when-a-labels-applied.

**Comment by prashant1380** [comment] 2020-02-24 14:57
Ok so only Co-owner can change the label. If this is the case, then definitely I am hit with some issue because Reviewer, Co-Author is also able to change the label. Seems like there is an issue in label policy.

**Comment by cabailey** [comment] 2020-02-24 17:19
I can't reproduce this (testing a label with user-defined permissions and then selecting Reviewer) so file that support ticket after checking your testing is robust - for example, the user who applies the label with Reviewer permissions is not the same user who opens the document on another computer (and make sure that second user isn't a super user).  On that second computer, when you open the document, you should see the RESTRICTED ACCESS banner, and when you select View Permissions, you should see No for Full Control and Export, with the result being no ability to set permissions or remove the permissions.  In my case, I didn't select a different label because I was testing across tenants, but the end result should be the same - you shouldn't be able to change the label if the permissions don't include Export or Full Control.

**Comment by cabailey** [comment] 2020-02-27 03:17
@prashant1380 Closing after confirming nothing to update in the docs.  If you find out further information after filing the support ticket, you can still update this thread.

**Closed by cabailey** 2020-02-27 03:17 UTC
Labels: compliance
