### ISSUE TITLE
Text Notifications in Microsoft Booking

### ISSUE THREAD

**Issue by huntjr1** [MicrosoftDocs/microsoft-365-docs#6738] opened 2021-10-29 16:44 UTC
Any known issues with the text reminders from Microsoft booking? I have clients setting up appointments for 140 pm (for example) and they will get a text that their appointment is confirmed for 840 am.  I've looked through the set up and can't find any issues.  Any help would be appreciated!  Below are screen shots: 

Received by client
![image](https://user-images.githubusercontent.com/93398373/139472247-ab1e8b84-3bca-4c2f-94cb-5b84ae26e1de.png)

Booking received by myself and client via email: 

![image](https://user-images.githubusercontent.com/93398373/139472366-74166ef2-9543-4800-ba9b-bc0b03293dcd.png)

**Comment by msbemba** [comment] 2021-11-03 21:35
@huntjr1 Thank you for your feedback. This looks like a bug on the tenant as I'm not able to reproduce this issue. We recommend you to contact Microsoft support via the need help section on the admin center to report this issue and have them fix.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment] 2021-11-09 06:58
@msbemba Thank you very much for the contribution and sharing this explanation. @huntjr1 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2021-11-09 06:58 UTC
Labels: Bookings, support-request
